{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/build.25/bb-data-structure-build.25.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "build.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-js-build.25.klib",
          "url": "bb-data-structure-js-build.25.klib",
          "size": 195207,
          "sha512": "2753a841a81e23bb6ee2126a7315eb8388d101abe90b2c54a398c71640db069b15df9307cbf9c363c849a546cbebf078835afd4605835fd15ec2f4e83d6fe4ce",
          "sha256": "22de6524f9c2445659aba50a6cca2a41371e9e257e0cd947e1c8589272be8d80",
          "sha1": "b9125135d6c59a16d85668d3244ac39c5a738383",
          "md5": "8fd75f788e68fe80a0e8f9eb97edc2ea"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-js-build.25.klib",
          "url": "bb-data-structure-js-build.25.klib",
          "size": 195207,
          "sha512": "2753a841a81e23bb6ee2126a7315eb8388d101abe90b2c54a398c71640db069b15df9307cbf9c363c849a546cbebf078835afd4605835fd15ec2f4e83d6fe4ce",
          "sha256": "22de6524f9c2445659aba50a6cca2a41371e9e257e0cd947e1c8589272be8d80",
          "sha1": "b9125135d6c59a16d85668d3244ac39c5a738383",
          "md5": "8fd75f788e68fe80a0e8f9eb97edc2ea"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "bb-data-structure-js-build.25-sources.jar",
          "url": "bb-data-structure-js-build.25-sources.jar",
          "size": 15940,
          "sha512": "bf3fcc9722e2542da2b8a91b52bc86dd09d3c98a31d7af3a941eb3c1aa78a20e5babd866f0de347983f8b77a5f2c2fdf6baf482e73c364bb0d4b1341f7c1664e",
          "sha256": "504d5593bc3e1405dfb042bd233fbc95e24339e7ea5585c5171395d2f5f3fdba",
          "sha1": "a41cabdd3822425292ef1881a3dac0d800d2ddf1",
          "md5": "dacc82048b2d2df33ce438e38c7e2cc1"
        }
      ]
    }
  ]
}
