{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/4.1/bb-data-structure-4.1.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "rsrlcfmwznhinfyhocpav4nvdq"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-js-4.1.jar",
          "url": "bb-data-structure-js-4.1.jar",
          "size": 36862,
          "sha512": "f250027d6eb341006bc8d685d82bda8c482b51a0f640fded4c231f8cb72adc014248e36cb7c7e9bc42dd866b1bbf2e576f84f0a670d36e749e2752814e946c09",
          "sha256": "b87de5ebfb60287b16c6cf7c2dc3a988182537a06265a1bebf8b5fe9fa9567d4",
          "sha1": "c8c7786100ad68b9bf570d5548446b6bc96fb58e",
          "md5": "dfcd68fa03266646b9f40fdc7d8d4ab2"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-js-4.1.jar",
          "url": "bb-data-structure-js-4.1.jar",
          "size": 36862,
          "sha512": "f250027d6eb341006bc8d685d82bda8c482b51a0f640fded4c231f8cb72adc014248e36cb7c7e9bc42dd866b1bbf2e576f84f0a670d36e749e2752814e946c09",
          "sha256": "b87de5ebfb60287b16c6cf7c2dc3a988182537a06265a1bebf8b5fe9fa9567d4",
          "sha1": "c8c7786100ad68b9bf570d5548446b6bc96fb58e",
          "md5": "dfcd68fa03266646b9f40fdc7d8d4ab2"
        }
      ]
    }
  ]
}
