{
  "formatVersion": "1.1",
  "component": {
    "url": "../../uuid-serializer/1.1/uuid-serializer-1.1.module",
    "group": "net.lepinoid",
    "module": "uuid-serializer",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "uuid-serializer.klib",
          "url": "uuid-serializer-native-1.1.klib",
          "size": 6328,
          "sha512": "6c4b1c62d3699027c2b3ec4a7efc4eb9db05008cb2b4e81260c6894996ebcefff4d936e1fa14d6e577ee50eb5340acf0f5b1d7d4a48cbdcf347e78cc9344c194",
          "sha256": "59d9195a8f1952a5f4f5be4c1ed6b981208cd33b98c592b3628a0929d52d3efc",
          "sha1": "c53b3b6cb6c4623d4664758d32345130836097c3",
          "md5": "cfc43bd8b4cff613caf32af3686430e5"
        }
      ]
    }
  ]
}
