{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.19.1+build.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.7.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.7.jar",
          "size": 58734,
          "sha512": "14f704535023e3dd0b5de1cdab4911b14133b5664a997f169aea0f58f82a7ba1d4b639508171c00f47898a514ad29f855ad505e46fef2ee1ff4fe7510131c68e",
          "sha256": "a77452752aeab6d62b24d1a47d6b35a96bbfe1a2334019ce04c927d9e942ca3e",
          "sha1": "99ff107a6cdff26b0d2f534350ceb652e0bdd3e1",
          "md5": "d7798ea45c794453e776ef68cfc36a39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.19.1+build.7"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.9+e62f51a395"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.5+0c17ea9695"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.1.0+33fbc73895"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.21+23c4cfef95"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.5.6+5f1a85e095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.18+9ff28f4095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.1+3082331495"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.7.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.7.jar",
          "size": 58734,
          "sha512": "14f704535023e3dd0b5de1cdab4911b14133b5664a997f169aea0f58f82a7ba1d4b639508171c00f47898a514ad29f855ad505e46fef2ee1ff4fe7510131c68e",
          "sha256": "a77452752aeab6d62b24d1a47d6b35a96bbfe1a2334019ce04c927d9e942ca3e",
          "sha1": "99ff107a6cdff26b0d2f534350ceb652e0bdd3e1",
          "md5": "d7798ea45c794453e776ef68cfc36a39"
        }
      ]
    }
  ]
}
