{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-metadata-build.25.jar",
          "url": "model-meta-build.25.jar",
          "size": 4479,
          "sha512": "6381d8fdc9d9c687c31ba2ea12d53268e2f6f61c8218b408cc198048580f9c7ae4e4a367848f2e539b7bf7b8d37b49fbae42e0116ebd8e4052294b53de477544",
          "sha256": "9f827b4d6927f53c1fee407ac6a5ef4fbb16699d783a801b402eb82a5d3cff5d",
          "sha1": "973ba55e02b50c1a0d107bc6db5520cb5d2da043",
          "md5": "897506c128f004a8935228dc83feb1bc"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "model-meta-kotlin-build.25-sources.jar",
          "url": "model-meta-build.25-sources.jar",
          "size": 1056,
          "sha512": "23a3302c46dcac55a9f7e8b79bd4fd2bf8e3c3a334c2b8d80900363242aacbab979abbfb68225adc18fa3a72bbcac998cb2da2831acb989e790da4913965ade8",
          "sha256": "695be92ff69a8c77161f44f8dde0fc0b9e53fa5179fe8e8e95fff65a0c561532",
          "sha1": "a80c62218de71f380ffa5ed56ab71c894a905184",
          "md5": "92f497249536faaf692eafc223da5578"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-meta-js/build.25/model-meta-js-build.25.module",
        "group": "net.lepinoid",
        "module": "model-meta-js",
        "version": "build.25"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-meta-js/build.25/model-meta-js-build.25.module",
        "group": "net.lepinoid",
        "module": "model-meta-js",
        "version": "build.25"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-meta-js/build.25/model-meta-js-build.25.module",
        "group": "net.lepinoid",
        "module": "model-meta-js",
        "version": "build.25"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-meta-jvm/build.25/model-meta-jvm-build.25.module",
        "group": "net.lepinoid",
        "module": "model-meta-jvm",
        "version": "build.25"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-meta-jvm/build.25/model-meta-jvm-build.25.module",
        "group": "net.lepinoid",
        "module": "model-meta-jvm",
        "version": "build.25"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-meta-jvm/build.25/model-meta-jvm-build.25.module",
        "group": "net.lepinoid",
        "module": "model-meta-jvm",
        "version": "build.25"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-meta-native/build.25/model-meta-native-build.25.module",
        "group": "net.lepinoid",
        "module": "model-meta-native",
        "version": "build.25"
      }
    },
    {
      "name": "nativeSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-meta-native/build.25/model-meta-native-build.25.module",
        "group": "net.lepinoid",
        "module": "model-meta-native",
        "version": "build.25"
      }
    }
  ]
}
