{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.7/model-meta-build.7.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta.klib",
          "url": "model-meta-native-build.7.klib",
          "size": 17469,
          "sha512": "431a30ca16aec44643a4a08b86c2d915ef369cd549e9712cbfdc27b448ea8e0e9efe764b276556a77f8bdd2c98ed6035458a8aeffd4b5fd01f52c9d1fd71500b",
          "sha256": "49dce32510828f49e25f3a3bca0ff5f1c2db5b77cbb23e3d064cbb0f1a578dc3",
          "sha1": "bcbc452a399646142fbe678a922c2248a84adcc8",
          "md5": "f24a9ea0e9e7c2d37f1ec3f744ec473a"
        }
      ]
    }
  ]
}
