{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "build.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-metadata-build.7.jar",
          "url": "bb-data-structure-build.7.jar",
          "size": 16504,
          "sha512": "8e5c221b4ae53a3c1cfd6f85334e22a29ddc75eecd51c43f991543ea8b47060c7e83c88ae99f0f9048cf6eb4759469ad00a0f478efac25bc925012ccdeddf41d",
          "sha256": "800058af1fbef1bf06fa049c2bbf5f1e865e0e77ad877888ec2b270db39c6ab8",
          "sha1": "efeba959665515c843df823a4d372d0467e510bb",
          "md5": "a480a8b5fecca5864b1a68db5355b59c"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/build.7/bb-data-structure-js-build.7.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "build.7"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/build.7/bb-data-structure-js-build.7.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "build.7"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/build.7/bb-data-structure-jvm-build.7.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "build.7"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/build.7/bb-data-structure-jvm-build.7.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "build.7"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bb-data-structure-native/build.7/bb-data-structure-native-build.7.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-native",
        "version": "build.7"
      }
    }
  ]
}
