{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bbdatastructure/3.0/bbdatastructure-3.0.module",
    "group": "net.lepinoid",
    "module": "bbdatastructure",
    "version": "3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "k7w6k3jjgbfz5d354hfxaxqfnu"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-js-3.0.jar",
          "url": "bbdatastructure-js-3.0.jar",
          "size": 35971,
          "sha512": "48915f2e87bb14e81ace59a43a6bafd14c8a621163505895965a959e5fca94ef8650928d2c8addb4d47181d19dcf82875e2db2dbaaec3124f49d60b863fcccf7",
          "sha256": "b5a5d490537671f7cb0e605cf34111f9c28028c35017f94ce8d3bd7055d2b422",
          "sha1": "f30695155b70fc319a5bfecdfe82a7c07652f6d1",
          "md5": "123188049e439bb567d8ad9a72bdc227"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-js-3.0.jar",
          "url": "bbdatastructure-js-3.0.jar",
          "size": 35971,
          "sha512": "48915f2e87bb14e81ace59a43a6bafd14c8a621163505895965a959e5fca94ef8650928d2c8addb4d47181d19dcf82875e2db2dbaaec3124f49d60b863fcccf7",
          "sha256": "b5a5d490537671f7cb0e605cf34111f9c28028c35017f94ce8d3bd7055d2b422",
          "sha1": "f30695155b70fc319a5bfecdfe82a7c07652f6d1",
          "md5": "123188049e439bb567d8ad9a72bdc227"
        }
      ]
    }
  ]
}
