{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.19.1+build.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.5.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.5.jar",
          "size": 58629,
          "sha512": "1d124f3a3c1212b89a0173906e1001c4bc74835ff3b7cf0c9490cfd3d2b8360a76054400f5ce008c8b6c67919b2b99cd9632827ef029af839c3f16c766aac503",
          "sha256": "994b7f0b256f20ff94d8f8658639fa0adb6feec80523211cc56d3046561f53b5",
          "sha1": "5f2900fd900d69c148fac028e3fb8dd66af8d0fb",
          "md5": "7e1d4274208cc98b24af85d4d6d9b183"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.19.1+build.5"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.9+e62f51a395"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.5+0c17ea9695"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.1.0+33fbc73895"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.21+23c4cfef95"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.5.6+5f1a85e095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.18+9ff28f4095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.1+3082331495"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.5.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.5.jar",
          "size": 58629,
          "sha512": "1d124f3a3c1212b89a0173906e1001c4bc74835ff3b7cf0c9490cfd3d2b8360a76054400f5ce008c8b6c67919b2b99cd9632827ef029af839c3f16c766aac503",
          "sha256": "994b7f0b256f20ff94d8f8658639fa0adb6feec80523211cc56d3046561f53b5",
          "sha1": "5f2900fd900d69c148fac028e3fb8dd66af8d0fb",
          "md5": "7e1d4274208cc98b24af85d4d6d9b183"
        }
      ]
    }
  ]
}
