{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.19.1+build.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.11.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.11.jar",
          "size": 66784,
          "sha512": "0743cb8fa0e72bfb6f141ed9097173ba1e7621d6474ff85574efc933d6c62e6fb1590def24c4c19b243f7cad0ef595cb3ac6f0c5937982db8f42471af01fd780",
          "sha256": "a927c9a13e9ce51e31c8de0fa27c1af113c06e264334132a59ddeb514683528e",
          "sha1": "0b635663a8efa0e9ad46ea299841f937be019563",
          "md5": "7c5396a5b29331b4b2e54502cedc4df8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.19.1+build.11"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.9+e62f51a395"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.5+0c17ea9695"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.1.0+33fbc73895"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.21+23c4cfef95"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.5.6+5f1a85e095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.18+9ff28f4095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.1+3082331495"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.11.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.11.jar",
          "size": 66784,
          "sha512": "0743cb8fa0e72bfb6f141ed9097173ba1e7621d6474ff85574efc933d6c62e6fb1590def24c4c19b243f7cad0ef595cb3ac6f0c5937982db8f42471af01fd780",
          "sha256": "a927c9a13e9ce51e31c8de0fa27c1af113c06e264334132a59ddeb514683528e",
          "sha1": "0b635663a8efa0e9ad46ea299841f937be019563",
          "md5": "7c5396a5b29331b4b2e54502cedc4df8"
        }
      ]
    }
  ]
}
