{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.21.1+build.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.21.1+build.24.jar",
          "url": "lepinoid-client-fabric-1.21.1+build.24.jar",
          "size": 68224,
          "sha512": "6f7ba597a1a932b83a3ead22816d545779858d2836075431802f2d8dc0bd3fba66c7356321ec0a2a7d7c44827ac6eaf1cf430ba962adfb909650b77ae499abc7",
          "sha256": "6988d5e5dbee81ae3e3b3fb05f0fa73945db981ee90b2d1f1252402073e380c3",
          "sha1": "ad557d2531410da6e9b228f2402be14d7b09905e",
          "md5": "9dbf8c07baffe789e789a16bdf40f7da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.21.1+build.24"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.42+6573ed8c19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.2.28+6ced4dd919"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.3.12+6c1df36019"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "5.1.3+60c3209b19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "1.3.0+5659912919"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.47+0af3f5a719"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "4.3.0+c7469b2119"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.21.1+build.24.jar",
          "url": "lepinoid-client-fabric-1.21.1+build.24.jar",
          "size": 68224,
          "sha512": "6f7ba597a1a932b83a3ead22816d545779858d2836075431802f2d8dc0bd3fba66c7356321ec0a2a7d7c44827ac6eaf1cf430ba962adfb909650b77ae499abc7",
          "sha256": "6988d5e5dbee81ae3e3b3fb05f0fa73945db981ee90b2d1f1252402073e380c3",
          "sha1": "ad557d2531410da6e9b228f2402be14d7b09905e",
          "md5": "9dbf8c07baffe789e789a16bdf40f7da"
        }
      ]
    }
  ]
}
