{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.7/model-meta-build.7.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.7.klib",
          "url": "model-meta-js-build.7.klib",
          "size": 15150,
          "sha512": "78eaad3be6878b82c41482e05ee0c038d3696396fcc59fc084b3357eddb09c5779611e7562a6623d5430385688ee325ded9f2116d71c3db138fb6d651c13c62f",
          "sha256": "b85ef22d39f2f4fb7f9ec098405bf4c6401cc1142a704d8195ed6e4d26bd8a69",
          "sha1": "aacc6f5b016faea2f2ebecb137824688690a4248",
          "md5": "d2f5be0d5a8eefa52ac95d4c2908d826"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.7.klib",
          "url": "model-meta-js-build.7.klib",
          "size": 15150,
          "sha512": "78eaad3be6878b82c41482e05ee0c038d3696396fcc59fc084b3357eddb09c5779611e7562a6623d5430385688ee325ded9f2116d71c3db138fb6d651c13c62f",
          "sha256": "b85ef22d39f2f4fb7f9ec098405bf4c6401cc1142a704d8195ed6e4d26bd8a69",
          "sha1": "aacc6f5b016faea2f2ebecb137824688690a4248",
          "md5": "d2f5be0d5a8eefa52ac95d4c2908d826"
        }
      ]
    }
  ]
}
