{
  "formatVersion": "1.1",
  "component": {
    "url": "../../uuid-serializer/1.0/uuid-serializer-1.0.module",
    "group": "net.lepinoid",
    "module": "uuid-serializer",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "uuid-serializer.klib",
          "url": "uuid-serializer-native-1.0.klib",
          "size": 5960,
          "sha512": "9d42b225b2b629ec98b963bb78905512d6782e3eadd6e22ee467e2d554c9626ce793ca677e674e4755d48ce2ba41ee73d2e788895a6aa98e7d2355557e6d7b6b",
          "sha256": "dcaf5b5a2f46108e6bf558a6278fcdbe20053cfd54d29498dcdc3306d1c6c8aa",
          "sha1": "c61a16bd4029d82f5667494b8a3f4a4cb2c3f0f9",
          "md5": "1812567b7fe73ecb013b12fdf2b11215"
        }
      ]
    }
  ]
}
