{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.27/model-meta-build.27.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.27.klib",
          "url": "model-meta-js-build.27.klib",
          "size": 17755,
          "sha512": "92d23cca07d8ce367f65bf188a47ec9f677590c37d93bbc48ebe354f1dad1232fbc1d187069361dcca73ba598e9db642fdfb59a6c7e1d1e0cced7eb54065f8f8",
          "sha256": "a3eb8ca5f1d272c38aa4d46bea64ea0d5a631621658fd55bc10e00e0b6b46806",
          "sha1": "7575e2e30518ecad4c5738f03e4f21123587ef5b",
          "md5": "5c693b51c3022cd66da5ff8e49c7b3a8"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "build.24"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.27.klib",
          "url": "model-meta-js-build.27.klib",
          "size": 17755,
          "sha512": "92d23cca07d8ce367f65bf188a47ec9f677590c37d93bbc48ebe354f1dad1232fbc1d187069361dcca73ba598e9db642fdfb59a6c7e1d1e0cced7eb54065f8f8",
          "sha256": "a3eb8ca5f1d272c38aa4d46bea64ea0d5a631621658fd55bc10e00e0b6b46806",
          "sha1": "7575e2e30518ecad4c5738f03e4f21123587ef5b",
          "md5": "5c693b51c3022cd66da5ff8e49c7b3a8"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "model-meta-js-build.27-sources.jar",
          "url": "model-meta-js-build.27-sources.jar",
          "size": 1056,
          "sha512": "23a3302c46dcac55a9f7e8b79bd4fd2bf8e3c3a334c2b8d80900363242aacbab979abbfb68225adc18fa3a72bbcac998cb2da2831acb989e790da4913965ade8",
          "sha256": "695be92ff69a8c77161f44f8dde0fc0b9e53fa5179fe8e8e95fff65a0c561532",
          "sha1": "a80c62218de71f380ffa5ed56ab71c894a905184",
          "md5": "92f497249536faaf692eafc223da5578"
        }
      ]
    }
  ]
}
