{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.19.1+build.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.12.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.12.jar",
          "size": 71175,
          "sha512": "044a56ee3b2e549fbe9d2e642d90c926deec0dd982bd7f20cb0346e7c5e309aa0478ffd6b12f7ec2a403265d9366740c336b6578aa280cc8fbc78ca7f52371e7",
          "sha256": "038750f2d9cbb27c91374fe86ebc734aa7e253ff4ff877ce3b41fa7f4d1e859b",
          "sha1": "862ca39294a64c46f1a3f9ece6dc12918ec00e74",
          "md5": "98ed34e97ad4969a0c67e3ca714496d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.19.1+build.12"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.9+e62f51a395"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.5+0c17ea9695"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.1.0+33fbc73895"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.21+23c4cfef95"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.5.6+5f1a85e095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.18+9ff28f4095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.1+3082331495"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.12.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.12.jar",
          "size": 71175,
          "sha512": "044a56ee3b2e549fbe9d2e642d90c926deec0dd982bd7f20cb0346e7c5e309aa0478ffd6b12f7ec2a403265d9366740c336b6578aa280cc8fbc78ca7f52371e7",
          "sha256": "038750f2d9cbb27c91374fe86ebc734aa7e253ff4ff877ce3b41fa7f4d1e859b",
          "sha1": "862ca39294a64c46f1a3f9ece6dc12918ec00e74",
          "md5": "98ed34e97ad4969a0c67e3ca714496d7"
        }
      ]
    }
  ]
}
