{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/build.29/bb-data-structure-build.29.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "build.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure.klib",
          "url": "bb-data-structure-native-build.29.klib",
          "size": 183032,
          "sha512": "2fd1aef2126920f58a287d624315881cdf13794e9a624cef767161879c12ecf58b46f044fec3db93625b7aba0c8ef040d3a075b148cd0bba7a8f7dcb1fd89b89",
          "sha256": "bfccf5ed35b8efb4cc0ddcf5fb83fb48daff63e002e7af13bfa1ae89b4bc7781",
          "sha1": "03f910e3d6e26f5dc912826bee3b2b635db28b99",
          "md5": "d0fcf54175af7d28d5e12b689d43d77e"
        }
      ]
    },
    {
      "name": "nativeSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "bb-data-structure-native-build.29-sources.jar",
          "url": "bb-data-structure-native-build.29-sources.jar",
          "size": 15940,
          "sha512": "bf3fcc9722e2542da2b8a91b52bc86dd09d3c98a31d7af3a941eb3c1aa78a20e5babd866f0de347983f8b77a5f2c2fdf6baf482e73c364bb0d4b1341f7c1664e",
          "sha256": "504d5593bc3e1405dfb042bd233fbc95e24339e7ea5585c5171395d2f5f3fdba",
          "sha1": "a41cabdd3822425292ef1881a3dac0d800d2ddf1",
          "md5": "dacc82048b2d2df33ce438e38c7e2cc1"
        }
      ]
    }
  ]
}
