{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/5.0/bb-data-structure-5.0.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "yde5rbhbxnc3bb77vxgulxbcrm"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure.klib",
          "url": "bb-data-structure-native-5.0.klib",
          "size": 115382,
          "sha512": "979df637d2e0897fceaf1f734d096038af254f892c66983fb4a81c6b051a68331e75eac38984e19e785fd029ecf60044784736bba8af55419aac266f092d675d",
          "sha256": "2be7267248cf2dbabb0c7fe6c2b483f71eafc79cc8b514195ef540ecab6902f2",
          "sha1": "e37f0c3485876f5849307738332f4cddc13b81ac",
          "md5": "a39c3e14600220ed1043e5a0c8a6c0b6"
        }
      ]
    }
  ]
}
