{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-metadata-build.15.jar",
          "url": "model-meta-build.15.jar",
          "size": 4442,
          "sha512": "f7bc28adad8099eb1e3e646a49e74dcf0f1cad253faee3cd1ad5639dd2d265558b2ee5fafce7d37f297c48fabcd81dc464bc51bc924dc2a28421c52ec79e2c12",
          "sha256": "8c249f107bf15b02ae4307ba59c9ed56d54f052c941d010ebc4b2fe9c3c6f109",
          "sha1": "81199a7a6e990fd871004d7265dc86aff8b51c41",
          "md5": "67cea92e4b41bf42ffa67de6e4df1f90"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-meta-js/build.15/model-meta-js-build.15.module",
        "group": "net.lepinoid",
        "module": "model-meta-js",
        "version": "build.15"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-meta-js/build.15/model-meta-js-build.15.module",
        "group": "net.lepinoid",
        "module": "model-meta-js",
        "version": "build.15"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-meta-jvm/build.15/model-meta-jvm-build.15.module",
        "group": "net.lepinoid",
        "module": "model-meta-jvm",
        "version": "build.15"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-meta-jvm/build.15/model-meta-jvm-build.15.module",
        "group": "net.lepinoid",
        "module": "model-meta-jvm",
        "version": "build.15"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-meta-native/build.15/model-meta-native-build.15.module",
        "group": "net.lepinoid",
        "module": "model-meta-native",
        "version": "build.15"
      }
    }
  ]
}
