{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.14/model-meta-build.14.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "build.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.14.klib",
          "url": "model-meta-js-build.14.klib",
          "size": 15150,
          "sha512": "860d4dace56518b0dbade13df5a536d0e0fa648d7254c74235b4307b37be9b2b72a8ff210f7923624852f1758aac98a44869ec6b4da6a7df300cce9bb8879c7c",
          "sha256": "f280257ef82cfa8f1bf0b29da11ab3d996d6b7747f896f0ff3264bb5885e6392",
          "sha1": "f3d051868e2bd7c257286a0b6549d22149ed0c3a",
          "md5": "2e76bc182f710ebf6d33cb2b03eb5f70"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "build.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.14.klib",
          "url": "model-meta-js-build.14.klib",
          "size": 15150,
          "sha512": "860d4dace56518b0dbade13df5a536d0e0fa648d7254c74235b4307b37be9b2b72a8ff210f7923624852f1758aac98a44869ec6b4da6a7df300cce9bb8879c7c",
          "sha256": "f280257ef82cfa8f1bf0b29da11ab3d996d6b7747f896f0ff3264bb5885e6392",
          "sha1": "f3d051868e2bd7c257286a0b6549d22149ed0c3a",
          "md5": "2e76bc182f710ebf6d33cb2b03eb5f70"
        }
      ]
    }
  ]
}
