{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.6/model-meta-build.6.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.6.klib",
          "url": "model-meta-js-build.6.klib",
          "size": 13158,
          "sha512": "0f445ff659792378ddfba348de436bf928ee6228ebcf9c6e80af3f467db14e84595015154a6e5bcf4c71765831e0e9d0459eb702b23699f80ae9d4701658c1ee",
          "sha256": "9fde8a490251ad787ff68aa08ebf55931d92b18df307e19744a49444ee93f879",
          "sha1": "9591dbaa24f6e89d04a7663c6b1ff7adc2cb7715",
          "md5": "90f43d7818db8b3d879395346f6e56ec"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.6.klib",
          "url": "model-meta-js-build.6.klib",
          "size": 13158,
          "sha512": "0f445ff659792378ddfba348de436bf928ee6228ebcf9c6e80af3f467db14e84595015154a6e5bcf4c71765831e0e9d0459eb702b23699f80ae9d4701658c1ee",
          "sha256": "9fde8a490251ad787ff68aa08ebf55931d92b18df307e19744a49444ee93f879",
          "sha1": "9591dbaa24f6e89d04a7663c6b1ff7adc2cb7715",
          "md5": "90f43d7818db8b3d879395346f6e56ec"
        }
      ]
    }
  ]
}
