{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.30/model-meta-build.30.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.30.klib",
          "url": "model-meta-js-build.30.klib",
          "size": 17756,
          "sha512": "6ef4cd8e18858fd2a0eabf93662813306390a46a3cdd1ceb435a6bf66bce5f677e759c28c9699675b8d140ba1c73bf69efbf92b4733a10fb964ec16b430ba0c0",
          "sha256": "60eedef075e06c85c7647052a8a8cf13af14295ac0d5eb10c78e9be077587d26",
          "sha1": "5030551b38d0eb3b160d0dcdac04b5eab636f4e5",
          "md5": "3a0956477bd3ec81272023463c763361"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "build.24"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.30.klib",
          "url": "model-meta-js-build.30.klib",
          "size": 17756,
          "sha512": "6ef4cd8e18858fd2a0eabf93662813306390a46a3cdd1ceb435a6bf66bce5f677e759c28c9699675b8d140ba1c73bf69efbf92b4733a10fb964ec16b430ba0c0",
          "sha256": "60eedef075e06c85c7647052a8a8cf13af14295ac0d5eb10c78e9be077587d26",
          "sha1": "5030551b38d0eb3b160d0dcdac04b5eab636f4e5",
          "md5": "3a0956477bd3ec81272023463c763361"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "model-meta-js-build.30-sources.jar",
          "url": "model-meta-js-build.30-sources.jar",
          "size": 1056,
          "sha512": "23a3302c46dcac55a9f7e8b79bd4fd2bf8e3c3a334c2b8d80900363242aacbab979abbfb68225adc18fa3a72bbcac998cb2da2831acb989e790da4913965ade8",
          "sha256": "695be92ff69a8c77161f44f8dde0fc0b9e53fa5179fe8e8e95fff65a0c561532",
          "sha1": "a80c62218de71f380ffa5ed56ab71c894a905184",
          "md5": "92f497249536faaf692eafc223da5578"
        }
      ]
    }
  ]
}
