{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.19.1+build.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.9.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.9.jar",
          "size": 66704,
          "sha512": "ffbfd67aef88704403f8cd3755f0fea04d494d8f6fb8102c8abcbbadbb5d3177af840fdfcf6bf587650d9b6eaf164e75db311657db177fa30240ace1ff59c260",
          "sha256": "268a0b60b831b39dc96b0602e4ca049230cbcf1474f4e58cb1a90e8c092999c7",
          "sha1": "65207c81e57f766b694bf726d9ce95a2c427aba0",
          "md5": "5d33a477c79da624654453ad10ce2f9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.19.1+build.9"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.9+e62f51a395"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.5+0c17ea9695"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.1.0+33fbc73895"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.21+23c4cfef95"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.5.6+5f1a85e095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.18+9ff28f4095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.1+3082331495"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.9.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.9.jar",
          "size": 66704,
          "sha512": "ffbfd67aef88704403f8cd3755f0fea04d494d8f6fb8102c8abcbbadbb5d3177af840fdfcf6bf587650d9b6eaf164e75db311657db177fa30240ace1ff59c260",
          "sha256": "268a0b60b831b39dc96b0602e4ca049230cbcf1474f4e58cb1a90e8c092999c7",
          "sha1": "65207c81e57f766b694bf726d9ce95a2c427aba0",
          "md5": "5d33a477c79da624654453ad10ce2f9f"
        }
      ]
    }
  ]
}
