{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/4.2/bb-data-structure-4.2.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "b7knasy2qrdbpatqkrep6wrkvq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-jvm-4.2.jar",
          "url": "bb-data-structure-jvm-4.2.jar",
          "size": 147335,
          "sha512": "da64b13f91d5214ab86f820363b82c3ebd5c5b3fa18b626f0fffda62654d8246e0bd15895e90afe105450f9e802480f0c5715a1735eeed3facd8cfe53da6341c",
          "sha256": "28bfcd9a92cf349c1bf12d51ba1e0360627ac4bb0b83bf7c966c6d0864b6bc33",
          "sha1": "98985301a783265b719775cd2791f1becc8a8ea4",
          "md5": "f5c93f3e0ca0c5416fab1ce7a18e569f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-jvm-4.2.jar",
          "url": "bb-data-structure-jvm-4.2.jar",
          "size": 147335,
          "sha512": "da64b13f91d5214ab86f820363b82c3ebd5c5b3fa18b626f0fffda62654d8246e0bd15895e90afe105450f9e802480f0c5715a1735eeed3facd8cfe53da6341c",
          "sha256": "28bfcd9a92cf349c1bf12d51ba1e0360627ac4bb0b83bf7c966c6d0864b6bc33",
          "sha1": "98985301a783265b719775cd2791f1becc8a8ea4",
          "md5": "f5c93f3e0ca0c5416fab1ce7a18e569f"
        }
      ]
    }
  ]
}
