{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bbdatastructure/3.1/bbdatastructure-3.1.module",
    "group": "net.lepinoid",
    "module": "bbdatastructure",
    "version": "3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "zcafpatkdzhjzl4aiad4l4diea"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-js-3.1.jar",
          "url": "bbdatastructure-js-3.1.jar",
          "size": 36052,
          "sha512": "99d4f2ab07390e83742388bad230582b3805356f9550c7b1290428e7829dc475c5738b4a61d84915c3aaf02ce69308c5ea23549645201500ea02e76693976086",
          "sha256": "54ba6334836d404f1ae5c7d20277b0c5bba8367acc93e26d45899f2713a3628b",
          "sha1": "86233a6ffa1adfe77d3ab78acb8a1a2f161ee4ce",
          "md5": "f03232efa80cfcf2198d473311553e22"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-js-3.1.jar",
          "url": "bbdatastructure-js-3.1.jar",
          "size": 36052,
          "sha512": "99d4f2ab07390e83742388bad230582b3805356f9550c7b1290428e7829dc475c5738b4a61d84915c3aaf02ce69308c5ea23549645201500ea02e76693976086",
          "sha256": "54ba6334836d404f1ae5c7d20277b0c5bba8367acc93e26d45899f2713a3628b",
          "sha1": "86233a6ffa1adfe77d3ab78acb8a1a2f161ee4ce",
          "md5": "f03232efa80cfcf2198d473311553e22"
        }
      ]
    }
  ]
}
