{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/1.0/model-meta-1.0.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-1.0.jar",
          "url": "model-meta-js-1.0.jar",
          "size": 7366,
          "sha512": "5507ea15e7e01e739e480bcd86a809bd1969260504495e706abfe603dfa5ea67388b89ef25292681a8409dc99d86f4eec018b0c76038944efdafdaa27256e540",
          "sha256": "05a489e52c896730f1c7696c51e065e4d4955fdb48585b27ebd1979c5920ec3e",
          "sha1": "f7e97f092878ee915b0f9013c021203f1e6591e3",
          "md5": "a442a7d55d07386c486452e1696eed82"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bbdatastructure",
          "version": {
            "requires": "3.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-1.0.jar",
          "url": "model-meta-js-1.0.jar",
          "size": 7366,
          "sha512": "5507ea15e7e01e739e480bcd86a809bd1969260504495e706abfe603dfa5ea67388b89ef25292681a8409dc99d86f4eec018b0c76038944efdafdaa27256e540",
          "sha256": "05a489e52c896730f1c7696c51e065e4d4955fdb48585b27ebd1979c5920ec3e",
          "sha1": "f7e97f092878ee915b0f9013c021203f1e6591e3",
          "md5": "a442a7d55d07386c486452e1696eed82"
        }
      ]
    }
  ]
}
