{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "ue7ftjht2jfcrm5k3a4tlxpmpi"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-metadata-3.1-all.jar",
          "url": "bb-data-structure-3.1-all.jar",
          "size": 10734,
          "sha512": "6ea7d36715f9f40d3e08e59b53b7a7bd7a3326068af4382e7a77b20d630be93c5ffc0bc956f0a8761d08617c86d29e534b269619492a9ad766241e910f08a05b",
          "sha256": "38a01b86d35a0b594d8ca8a9b231f15379ca36a9d3363e36dd800ebaa43957c9",
          "sha1": "1c95d40553f1cd215d4dbc6c4db5e25b2fadf35f",
          "md5": "8a530eecb938c956be3ae79a1113b21b"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-3.1.jar",
          "url": "bb-data-structure-3.1.jar",
          "size": 27069,
          "sha512": "806b4141a6551d494788df2049056d3067208d6f408795ed85d09a50f5ba0c52a156c3d17473b4e078248fabf1585ede61e53cb06a80f5dacb5953a846543dcd",
          "sha256": "f41fc0916be07ffcb850dfd6003cdf42cd90aea48a27421b26157da5981f8e18",
          "sha1": "dbaab4c87fd81086606c95536efe14aa165728a0",
          "md5": "27a124c41829aefbb77982d769181a6b"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/3.1/bb-data-structure-js-3.1.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "3.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/3.1/bb-data-structure-js-3.1.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "3.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/3.1/bb-data-structure-jvm-3.1.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "3.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/3.1/bb-data-structure-jvm-3.1.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "3.1"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bb-data-structure-native/3.1/bb-data-structure-native-3.1.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-native",
        "version": "3.1"
      }
    }
  ]
}
