{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "build.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-metadata-build.2.jar",
          "url": "bb-data-structure-build.2.jar",
          "size": 15422,
          "sha512": "4e9a575f772567ddbf0e061ee4de8fa0bbf2e61c9647a569e953075e6c7f08b918e9aaa6045d206473b86e37a58ed8f32280399b743802ce9704b5d20ffd5a3a",
          "sha256": "4bae6d0db2bd8f16765354e40fb639117d5e960b5a1cac3dd40a3b17111c5dbd",
          "sha1": "e28d2a7ed19c883e8ba70c027e784cb9a99d50c2",
          "md5": "d0bb71d78a4998f70bb8e477d79931ac"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/build.2/bb-data-structure-js-build.2.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "build.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/build.2/bb-data-structure-js-build.2.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "build.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/build.2/bb-data-structure-jvm-build.2.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "build.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/build.2/bb-data-structure-jvm-build.2.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "build.2"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bb-data-structure-native/build.2/bb-data-structure-native-build.2.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-native",
        "version": "build.2"
      }
    }
  ]
}
