{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/0.2.1/bb-data-structure-0.2.1.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure.klib",
          "url": "bb-data-structure-native-0.2.1.klib",
          "size": 138479,
          "sha512": "23647191e7c3ac6aa16e5345d129bf853769a7805df81d139c60d1c856be895a80b7d671e276cb30f4eaf370c38de4e54cad18300b5dd7816e677da220885bd4",
          "sha256": "49ab249aac58353f01346f7de7b17cd65d8d5044f25025b66d3519cc85390c32",
          "sha1": "c07b030d4002c38f8adecf1f99b24c13ecf5d621",
          "md5": "9e08c62b2a9ec6011a9241a2fd73890e"
        }
      ]
    }
  ]
}
