{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "rsrlcfmwznhinfyhocpav4nvdq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-metadata-4.1-all.jar",
          "url": "bb-data-structure-4.1-all.jar",
          "size": 10753,
          "sha512": "436214273220a0c26a15fad25a6df23b5dc06897ad9d8c8f31dbc447a9c8fee1ba65be65d2aa1aaf924c3c2a6daa659c363230b0e656693ee1d054ca6c37379b",
          "sha256": "6daf05bf559687e1cabcb49a1c9c3be3863e1a557349f3dbc4ed08ae10cebbb0",
          "sha1": "be8a1cbf91c9592c7867f8b9a9ebc270b15d4833",
          "md5": "7fd54b79b41ebef62f677f84e6b83a89"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-4.1.jar",
          "url": "bb-data-structure-4.1.jar",
          "size": 27111,
          "sha512": "4bf2737d062e2d10e2180e731bbf7700545b6ad8ac9019e5ee3d0bfecdda67d78cebc67da1436b60f0f12a94a3965761d238db5dff7d2a9a0a0bb70e42e8eac8",
          "sha256": "9895f28cd596a06c85dfc87b52fccfbb203827d7d48e69cffdad027e0b97b371",
          "sha1": "65c64917c290d8a84191f235c1f113fc4ef29d56",
          "md5": "b6e9623f568eb92d3ce3b70d0ff6b6d8"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/4.1/bb-data-structure-js-4.1.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "4.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/4.1/bb-data-structure-js-4.1.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "4.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/4.1/bb-data-structure-jvm-4.1.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "4.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/4.1/bb-data-structure-jvm-4.1.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "4.1"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bb-data-structure-native/4.1/bb-data-structure-native-4.1.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-native",
        "version": "4.1"
      }
    }
  ]
}
