{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/build.25/bb-data-structure-build.25.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "build.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure.klib",
          "url": "bb-data-structure-native-build.25.klib",
          "size": 183032,
          "sha512": "10affc79f96a9b082b3aa6e5295b52975fc069123afdac983233d68d64459bd6b96729689920d87e5dcfb9a839b8d40234d170715a07fd42001582d6cec0a69f",
          "sha256": "b62a9c0e1b3fd0dace3b121727f283303b24a32f6ea7a567fbc1f308a637fa6a",
          "sha1": "04948e0734eb34be997b79b8d54bc715e1d9df15",
          "md5": "8d0daa1c5786f941f7b2ccae3711e33a"
        }
      ]
    },
    {
      "name": "nativeSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "bb-data-structure-native-build.25-sources.jar",
          "url": "bb-data-structure-native-build.25-sources.jar",
          "size": 15940,
          "sha512": "bf3fcc9722e2542da2b8a91b52bc86dd09d3c98a31d7af3a941eb3c1aa78a20e5babd866f0de347983f8b77a5f2c2fdf6baf482e73c364bb0d4b1341f7c1664e",
          "sha256": "504d5593bc3e1405dfb042bd233fbc95e24339e7ea5585c5171395d2f5f3fdba",
          "sha1": "a41cabdd3822425292ef1881a3dac0d800d2ddf1",
          "md5": "dacc82048b2d2df33ce438e38c7e2cc1"
        }
      ]
    }
  ]
}
