{
  "formatVersion": "1.1",
  "component": {
    "url": "../../uuid-serializer/1.2/uuid-serializer-1.2.module",
    "group": "net.lepinoid",
    "module": "uuid-serializer",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "uuid-serializer-js-1.2.klib",
          "url": "uuid-serializer-js-1.2.klib",
          "size": 4337,
          "sha512": "d3807e7a94cbab8dc42bd18b5aa7c595e37434a0d27be525665a3c6e7f8d2ba030d3952557e582a6f4dba2f21d09cbce1037dd2ed4a56bee3f1148ba06bff265",
          "sha256": "93462db3501b8a206182bb553c693b0332bb74544ad10cf2a585043f144df152",
          "sha1": "651835d9cc0c24445a10e83dbd6ce3d8b676e7d3",
          "md5": "13da8b5feb425814dd00ac0f4052e09a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "uuid-serializer-js-1.2.klib",
          "url": "uuid-serializer-js-1.2.klib",
          "size": 4337,
          "sha512": "d3807e7a94cbab8dc42bd18b5aa7c595e37434a0d27be525665a3c6e7f8d2ba030d3952557e582a6f4dba2f21d09cbce1037dd2ed4a56bee3f1148ba06bff265",
          "sha256": "93462db3501b8a206182bb553c693b0332bb74544ad10cf2a585043f144df152",
          "sha1": "651835d9cc0c24445a10e83dbd6ce3d8b676e7d3",
          "md5": "13da8b5feb425814dd00ac0f4052e09a"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "uuid-serializer-js-1.2-sources.jar",
          "url": "uuid-serializer-js-1.2-sources.jar",
          "size": 782,
          "sha512": "28bd3d6bbc69190a7cbdc28d40b1b8456fb4ad90d6d79d1c95154e6f10a11b6253d6831f6be57a54848dd6ce8700aee49f2d8a233a0e02731f3d0128f30a5a80",
          "sha256": "f6a9749a43e90316949b4c3ff1d2a14cd82779e3e39c6fcedf895e0455755d2b",
          "sha1": "21f128ed72cff5c6313812a5ecbe32f3ee76dba2",
          "md5": "2af842bfcd250c12c01df32fe82c6019"
        }
      ]
    }
  ]
}
