{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.24/model-meta-build.24.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.24.klib",
          "url": "model-meta-js-build.24.klib",
          "size": 17757,
          "sha512": "8cc9ba7c2ff5dda56609903620ae84735ee31c0b00fbba16b06a070050da2be0db6baa409edc0e5f5543c4f58339fcc75459ea4a5a3ba86a0118912350a305e5",
          "sha256": "e604f02fe794db11faaee7104ccc8045153223435dddfa8b0c7b26c990af4934",
          "sha1": "92362f9fc67a90ff08dce05c7f5db11ced493c3e",
          "md5": "2f7bb11d65e25cf5a5f59f0b40e98906"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.24.klib",
          "url": "model-meta-js-build.24.klib",
          "size": 17757,
          "sha512": "8cc9ba7c2ff5dda56609903620ae84735ee31c0b00fbba16b06a070050da2be0db6baa409edc0e5f5543c4f58339fcc75459ea4a5a3ba86a0118912350a305e5",
          "sha256": "e604f02fe794db11faaee7104ccc8045153223435dddfa8b0c7b26c990af4934",
          "sha1": "92362f9fc67a90ff08dce05c7f5db11ced493c3e",
          "md5": "2f7bb11d65e25cf5a5f59f0b40e98906"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "model-meta-js-build.24-sources.jar",
          "url": "model-meta-js-build.24-sources.jar",
          "size": 1056,
          "sha512": "23a3302c46dcac55a9f7e8b79bd4fd2bf8e3c3a334c2b8d80900363242aacbab979abbfb68225adc18fa3a72bbcac998cb2da2831acb989e790da4913965ade8",
          "sha256": "695be92ff69a8c77161f44f8dde0fc0b9e53fa5179fe8e8e95fff65a0c561532",
          "sha1": "a80c62218de71f380ffa5ed56ab71c894a905184",
          "md5": "92f497249536faaf692eafc223da5578"
        }
      ]
    }
  ]
}
