{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "b7knasy2qrdbpatqkrep6wrkvq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-metadata-4.2-all.jar",
          "url": "bb-data-structure-4.2-all.jar",
          "size": 10876,
          "sha512": "0eabcd4de48ab1810e54519d7ec9b2be80bfccf22484255ecad9a154802338f5a3adc0afbb54dc4c1dab16932c0b68eb1b789346cc01e3f0cad090aaa5d9978d",
          "sha256": "17238e1490dcc521a4a416f4748a52080f95e7629f202cccd12337f544e9d43b",
          "sha1": "b8a1ec2bfabf586c655c25becfd4dbec73d6b37d",
          "md5": "717cb22790e10202b4f3d84a92321bc3"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-4.2.jar",
          "url": "bb-data-structure-4.2.jar",
          "size": 27260,
          "sha512": "8f59174f23cc98978806929304bcfc3140c16891749e37d12cfbe09a270a05bfa3306fef0c2c9da0aa698a8724df3e97cecdc9e38c8c948712fd768b957ec165",
          "sha256": "eff4106a0270baceda9fa21ec53ecbd67f8a7db259c9731a1956a7659e3379ed",
          "sha1": "598de74a91f751ed8d9a4759698aacd56c35cc73",
          "md5": "0f6410f104f5b038aa6f4857266c135e"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/4.2/bb-data-structure-js-4.2.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "4.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/4.2/bb-data-structure-js-4.2.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "4.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/4.2/bb-data-structure-jvm-4.2.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "4.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/4.2/bb-data-structure-jvm-4.2.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "4.2"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bb-data-structure-native/4.2/bb-data-structure-native-4.2.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-native",
        "version": "4.2"
      }
    }
  ]
}
