{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.4/model-meta-build.4.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta.klib",
          "url": "model-meta-native-build.4.klib",
          "size": 15475,
          "sha512": "56f84dbe194352631a297171911e3fa4bf432dde23a0cb53561f3229b132837dd336c0949fb2697b8928fad7922dd9da28a52ca84ad9a4ee2771ff7b71971aaf",
          "sha256": "7ed86207721369a83627c3feab316680fe273d568b5824456a69d81c150a7d76",
          "sha1": "71d39abadb94eb8c7a1c71fc7a20870b2d57596e",
          "md5": "7ee95e878994a6986f5c061372afe2c4"
        }
      ]
    }
  ]
}
