{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-protocol",
    "version": "1.19.1+build.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-protocol-1.19.1+build.13.jar",
          "url": "lepinoid-client-protocol-1.19.1+build.13.jar",
          "size": 7254,
          "sha512": "320fad73d7035c3c33820375d52ef29ce53e89f069c805d74f950ce587966bf5b0926d549dd6eba1a3943307ec8e462c91d4f36cf7c24f2d1befd6fa5d5e07da",
          "sha256": "9228ef9f42a0f712120be9ae3fb03414d9a0af8cb293d9109fc5eab4bd9d2a6c",
          "sha1": "eaf5b4d9d4c0ed0f1cdb7b95cbfd67b360742b29",
          "md5": "914c47afbf859160ab192ae77408168d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-protocol-1.19.1+build.13.jar",
          "url": "lepinoid-client-protocol-1.19.1+build.13.jar",
          "size": 7254,
          "sha512": "320fad73d7035c3c33820375d52ef29ce53e89f069c805d74f950ce587966bf5b0926d549dd6eba1a3943307ec8e462c91d4f36cf7c24f2d1befd6fa5d5e07da",
          "sha256": "9228ef9f42a0f712120be9ae3fb03414d9a0af8cb293d9109fc5eab4bd9d2a6c",
          "sha1": "eaf5b4d9d4c0ed0f1cdb7b95cbfd67b360742b29",
          "md5": "914c47afbf859160ab192ae77408168d"
        }
      ]
    }
  ]
}
