{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.19+build.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19+build.1.jar",
          "url": "lepinoid-client-fabric-1.19+build.1.jar",
          "size": 25608,
          "sha512": "150740bb2dc90c1232521c1b0beec9b1db6047f5d0e245de092f3dda13283d061daff898f25ef626cce0eefdbc6e757c9faa8d057a60ccd9632394b205f7f831",
          "sha256": "61cc1c27a76693da370d2b1593095c5a21d8fd5f6759c93a9ab1f8bd47d5daf4",
          "sha1": "fc95ddc90fc0f95b838056a18e5a3a71635da062",
          "md5": "a025160aa66b14cbe5b8716a749e67f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.19+build.1"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.9+e62f51a3a9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.2+0d55f585a9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.1.0+33fbc738a9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.17+23c4cfefa9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.5.5+a6d2f785a9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.18+9ff28f40a9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.0.27+7fe97409a9"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19+build.1.jar",
          "url": "lepinoid-client-fabric-1.19+build.1.jar",
          "size": 25608,
          "sha512": "150740bb2dc90c1232521c1b0beec9b1db6047f5d0e245de092f3dda13283d061daff898f25ef626cce0eefdbc6e757c9faa8d057a60ccd9632394b205f7f831",
          "sha256": "61cc1c27a76693da370d2b1593095c5a21d8fd5f6759c93a9ab1f8bd47d5daf4",
          "sha1": "fc95ddc90fc0f95b838056a18e5a3a71635da062",
          "md5": "a025160aa66b14cbe5b8716a749e67f2"
        }
      ]
    }
  ]
}
