{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.14/model-meta-build.14.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "build.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta.klib",
          "url": "model-meta-native-build.14.klib",
          "size": 17469,
          "sha512": "69a510921817915c06cf85d0881a29d5882e8ebb1bbd76c27a191883790993e34802df46e0890c66378c00cae510f6cc1a9a9351ddf5f3b4c0c1b6a63ec49558",
          "sha256": "61e0e872b3513c34f303742cf59fc7c18d44c050e61458dfc130923644b74477",
          "sha1": "99a42870db6390db5eae6cfe5cefccdf915a0c9a",
          "md5": "6847d148cff410fb682bf79a137725d1"
        }
      ]
    }
  ]
}
