{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-metadata-build.1.jar",
          "url": "model-meta-build.1.jar",
          "size": 4316,
          "sha512": "940f00f941007862e4ceefe927d454e6be29357c8e90c36e90954ab97ce71b27df17947448d6b080a0d5325a65304073a50d564747d32537f4f101eaa4c802a0",
          "sha256": "243a533909875d598a41fea78d75d79224b71c3398dee5dc005bd09682aa68c5",
          "sha1": "850a52622570a7560b21d311c7064a2b0a799216",
          "md5": "e5294e2132023d9d093e32c5a1f27225"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-meta-js/build.1/model-meta-js-build.1.module",
        "group": "net.lepinoid",
        "module": "model-meta-js",
        "version": "build.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-meta-js/build.1/model-meta-js-build.1.module",
        "group": "net.lepinoid",
        "module": "model-meta-js",
        "version": "build.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-meta-jvm/build.1/model-meta-jvm-build.1.module",
        "group": "net.lepinoid",
        "module": "model-meta-jvm",
        "version": "build.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-meta-jvm/build.1/model-meta-jvm-build.1.module",
        "group": "net.lepinoid",
        "module": "model-meta-jvm",
        "version": "build.1"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-meta-native/build.1/model-meta-native-build.1.module",
        "group": "net.lepinoid",
        "module": "model-meta-native",
        "version": "build.1"
      }
    }
  ]
}
