{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-metadata-build.1.jar",
          "url": "model-meta-build.1.jar",
          "size": 4319,
          "sha512": "a15b78dd3d58b8e7a4dae126d92b46057cb741bfcb24e6389583b1cf1ea9a3c71b2a217dd74d1393864f672fa51cdca8f565090727a88a8521840f09e317ae5d",
          "sha256": "d1d78957429762950c678c170294674b7f43142fd5403d7ee16a3365ed21929e",
          "sha1": "efd776e3d65be3fa59638b153847d3363cd0ab86",
          "md5": "b04d008f8fbac3cf04414459bbaf7a05"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-meta-js/build.1/model-meta-js-build.1.module",
        "group": "net.lepinoid",
        "module": "model-meta-js",
        "version": "build.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-meta-js/build.1/model-meta-js-build.1.module",
        "group": "net.lepinoid",
        "module": "model-meta-js",
        "version": "build.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-meta-jvm/build.1/model-meta-jvm-build.1.module",
        "group": "net.lepinoid",
        "module": "model-meta-jvm",
        "version": "build.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-meta-jvm/build.1/model-meta-jvm-build.1.module",
        "group": "net.lepinoid",
        "module": "model-meta-jvm",
        "version": "build.1"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-meta-native/build.1/model-meta-native-build.1.module",
        "group": "net.lepinoid",
        "module": "model-meta-native",
        "version": "build.1"
      }
    }
  ]
}
