{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-metadata-build.1.jar",
          "url": "model-meta-build.1.jar",
          "size": 4316,
          "sha512": "3a3bc9f4b15f573e8b78fb95a5b57aa2d25c9b405e897d11b9d9b9ac4a62ce402408cbd54a0089ed250499e196fd3b00a09f22356a87e68591d0ac9ea4310129",
          "sha256": "399c47d9d5c5d34edf798096838f9277bb37834ecf0095ec0fb1658fd5bdc49a",
          "sha1": "879eb2a94c2451ba3f51902c325faa82ddd5c9d7",
          "md5": "6e3fb83205fae94171a8c0258b89fc9c"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-meta-js/build.1/model-meta-js-build.1.module",
        "group": "net.lepinoid",
        "module": "model-meta-js",
        "version": "build.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-meta-js/build.1/model-meta-js-build.1.module",
        "group": "net.lepinoid",
        "module": "model-meta-js",
        "version": "build.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-meta-jvm/build.1/model-meta-jvm-build.1.module",
        "group": "net.lepinoid",
        "module": "model-meta-jvm",
        "version": "build.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-meta-jvm/build.1/model-meta-jvm-build.1.module",
        "group": "net.lepinoid",
        "module": "model-meta-jvm",
        "version": "build.1"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-meta-native/build.1/model-meta-native-build.1.module",
        "group": "net.lepinoid",
        "module": "model-meta-native",
        "version": "build.1"
      }
    }
  ]
}
