{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/3.1/model-meta-3.1.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta.klib",
          "url": "model-meta-native-3.1.klib",
          "size": 15044,
          "sha512": "9b906e55ad14fa5b3b08a51baabcf4ed16c232d0b8dec6bcb342034b1115aa65bf2139f57083a29ec7b703b8451e2b3c4fcf298621dc0fa342ec953f785182db",
          "sha256": "b71bec6bcb2039e93defd954907df4239a64c291e9ee9ca5f3612ef844a7689c",
          "sha1": "0347684d84e522c2bfcb1f8245af96a6e0a8c925",
          "md5": "1b1118e4d3a0b88374e9f68d398f9493"
        }
      ]
    }
  ]
}
