{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bbdatastructure/3.1/bbdatastructure-3.1.module",
    "group": "net.lepinoid",
    "module": "bbdatastructure",
    "version": "3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "zcafpatkdzhjzl4aiad4l4diea"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-jvm-3.1.jar",
          "url": "bbdatastructure-jvm-3.1.jar",
          "size": 139309,
          "sha512": "8cbd3680888ab6b7c38a62c8abcb93daacc1ffc576c658a1491adfb1d6a5331ca0aa8a28c03c3b4ed27ea27a997ae6335845ca857cab5ab797124f16500ca2e8",
          "sha256": "495d9b242964dc18a87014f565d838f369d55270c0adeeaf9d462118577d3978",
          "sha1": "f6cbf0279ea9f0b4a9ea621865516de27b5bd530",
          "md5": "a4c78e776ded66ec50df4a94c010c075"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-jvm-3.1.jar",
          "url": "bbdatastructure-jvm-3.1.jar",
          "size": 139309,
          "sha512": "8cbd3680888ab6b7c38a62c8abcb93daacc1ffc576c658a1491adfb1d6a5331ca0aa8a28c03c3b4ed27ea27a997ae6335845ca857cab5ab797124f16500ca2e8",
          "sha256": "495d9b242964dc18a87014f565d838f369d55270c0adeeaf9d462118577d3978",
          "sha1": "f6cbf0279ea9f0b4a9ea621865516de27b5bd530",
          "md5": "a4c78e776ded66ec50df4a94c010c075"
        }
      ]
    }
  ]
}
