{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.21.8+build.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.21.8+build.30.jar",
          "url": "lepinoid-client-fabric-1.21.8+build.30.jar",
          "size": 70444,
          "sha512": "752c4d349f8dac1c6d75fee8cfc9303047cec602d1e972f1e17551c586bb7459a720eba073d226676b692f2548f15eca4b20db195413c0f30f8467f506fd73fe",
          "sha256": "ab03aa0cb192ca40d55c17f787f2cab1bb5242d4ef8f94f21aa8f9a9504e4f70",
          "sha1": "8dd92aed1132994f34a32aeafef15b09e434f709",
          "md5": "c1fcf67f0f5179bfb2f8bf815d7d1019"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.21.8+build.30"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.5.0+cd8c0daa2c"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.3.1+52fff9ec2c"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.6.4+db4dfd852c"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "6.1.30+946bf4c32c"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "3.1.12+020423442c"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.65+946bf4c32c"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "5.1.0+57cb96dd2c"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.21.8+build.30.jar",
          "url": "lepinoid-client-fabric-1.21.8+build.30.jar",
          "size": 70444,
          "sha512": "752c4d349f8dac1c6d75fee8cfc9303047cec602d1e972f1e17551c586bb7459a720eba073d226676b692f2548f15eca4b20db195413c0f30f8467f506fd73fe",
          "sha256": "ab03aa0cb192ca40d55c17f787f2cab1bb5242d4ef8f94f21aa8f9a9504e4f70",
          "sha1": "8dd92aed1132994f34a32aeafef15b09e434f709",
          "md5": "c1fcf67f0f5179bfb2f8bf815d7d1019"
        }
      ]
    }
  ]
}
