{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.19/model-meta-build.19.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta.klib",
          "url": "model-meta-native-build.19.klib",
          "size": 17470,
          "sha512": "34071188502524e75efce4b7cf4b13f65fe5ef95267d990770856e230b02e62d943475d4fac32c159cb20505a1aa8e231c3dcf3031ee5a906bd0c285f31dfdc2",
          "sha256": "a9e1cf6d1a0490da2e5f63f346557d014f085f3da20dbbd1bdf9f8d25ecba424",
          "sha1": "11e148fbe0aecb76eae516091f81e69391f089bf",
          "md5": "126420df823bca436a571ef5b5ed9c15"
        }
      ]
    }
  ]
}
