{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bbdatastructure/2.0/bbdatastructure-2.0.module",
    "group": "net.lepinoid",
    "module": "bbdatastructure",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "hshakwshxbfalagj2je7ygwa5u"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-jvm-2.0.jar",
          "url": "bbdatastructure-jvm-2.0.jar",
          "size": 136763,
          "sha512": "9f19d31a39d97a8186e0732eedf92b8c677150c2f96633b0291f6da98163c8917d40399bb0187f667afe245cbb25dde45b3229bb78723fb1c7746c3b461dfe85",
          "sha256": "c860ad527936945532ebdf57fccf677f5aec953d62bd4fb777cb889e08ce0908",
          "sha1": "98232bcfdef85cc48ff5ebdcdc8aaee210808df3",
          "md5": "ae9ced8379960dbbc9afb83ffbf51bf7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-jvm-2.0.jar",
          "url": "bbdatastructure-jvm-2.0.jar",
          "size": 136763,
          "sha512": "9f19d31a39d97a8186e0732eedf92b8c677150c2f96633b0291f6da98163c8917d40399bb0187f667afe245cbb25dde45b3229bb78723fb1c7746c3b461dfe85",
          "sha256": "c860ad527936945532ebdf57fccf677f5aec953d62bd4fb777cb889e08ce0908",
          "sha1": "98232bcfdef85cc48ff5ebdcdc8aaee210808df3",
          "md5": "ae9ced8379960dbbc9afb83ffbf51bf7"
        }
      ]
    }
  ]
}
