{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.21.1+build.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.21.1+build.25.jar",
          "url": "lepinoid-client-fabric-1.21.1+build.25.jar",
          "size": 71286,
          "sha512": "42e76a610b1f97872e326d83fd966a9fae8322bcc23595455edcf2a616b4943bf5b9e2f4bd8e4dcccabe0ce4ebca60e589f90037c79fd1a6061525997d0f372c",
          "sha256": "8754144236da2341931f6de910c6e464b4fff69abbc9c21d7283a2b75ff197e6",
          "sha1": "a49d8af808380939c8bd063c9709625639baf410",
          "md5": "43b94eaa7c2c369bcee7c50a3d385543"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.21.1+build.25"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.42+6573ed8c19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.2.28+6ced4dd919"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.3.12+6c1df36019"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "5.1.3+60c3209b19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "1.3.0+5659912919"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.47+0af3f5a719"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "4.3.0+c7469b2119"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.21.1+build.25.jar",
          "url": "lepinoid-client-fabric-1.21.1+build.25.jar",
          "size": 71286,
          "sha512": "42e76a610b1f97872e326d83fd966a9fae8322bcc23595455edcf2a616b4943bf5b9e2f4bd8e4dcccabe0ce4ebca60e589f90037c79fd1a6061525997d0f372c",
          "sha256": "8754144236da2341931f6de910c6e464b4fff69abbc9c21d7283a2b75ff197e6",
          "sha1": "a49d8af808380939c8bd063c9709625639baf410",
          "md5": "43b94eaa7c2c369bcee7c50a3d385543"
        }
      ]
    }
  ]
}
