{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.21.8+build.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.21.8+build.29.jar",
          "url": "lepinoid-client-fabric-1.21.8+build.29.jar",
          "size": 70446,
          "sha512": "f4c1558bc5ed4b57c175afb892e8e2764c1dd4086c9470c8a84688d56b142e3390c6f9746501e146ecfa514812833d3948c1002cd37af7334d6af12c5f05c4a2",
          "sha256": "fbcced1b7523c7ec7569338bfab042a501cc1dfed1349a1509956db7eb2a72a9",
          "sha1": "84b67b7af23d1a478ee9c8db4a0b0349f801af38",
          "md5": "e2497db9dcab8dcfb47e116c0010f40a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.21.8+build.29"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.5.0+cd8c0daa2c"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.3.1+52fff9ec2c"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.6.4+db4dfd852c"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "6.1.30+946bf4c32c"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "3.1.12+020423442c"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.65+946bf4c32c"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "5.1.0+57cb96dd2c"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.21.8+build.29.jar",
          "url": "lepinoid-client-fabric-1.21.8+build.29.jar",
          "size": 70446,
          "sha512": "f4c1558bc5ed4b57c175afb892e8e2764c1dd4086c9470c8a84688d56b142e3390c6f9746501e146ecfa514812833d3948c1002cd37af7334d6af12c5f05c4a2",
          "sha256": "fbcced1b7523c7ec7569338bfab042a501cc1dfed1349a1509956db7eb2a72a9",
          "sha1": "84b67b7af23d1a478ee9c8db4a0b0349f801af38",
          "md5": "e2497db9dcab8dcfb47e116c0010f40a"
        }
      ]
    }
  ]
}
