{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "build.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-metadata-build.1.jar",
          "url": "bb-data-structure-build.1.jar",
          "size": 14349,
          "sha512": "e50213bdb9cfbd12e99bb96d2d41eb962fb76223954840806928553ba8ca4ab7eaf95207d384ea35bbf460678dcc34f51e0d3d54c78b5f5b3041d948b7600299",
          "sha256": "b8b2b0057d1d5af04d515e17e0725e373225701e3497d6923135bcdc5399321e",
          "sha1": "69f016b4a62da6c47ac83219e659044fc73ad922",
          "md5": "4f9fb197b1fb3f259f35ae8436d04828"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/build.1/bb-data-structure-js-build.1.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "build.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/build.1/bb-data-structure-js-build.1.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "build.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/build.1/bb-data-structure-jvm-build.1.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "build.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/build.1/bb-data-structure-jvm-build.1.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "build.1"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bb-data-structure-native/build.1/bb-data-structure-native-build.1.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-native",
        "version": "build.1"
      }
    }
  ]
}
