{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/4.1/bb-data-structure-4.1.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "rsrlcfmwznhinfyhocpav4nvdq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-jvm-4.1.jar",
          "url": "bb-data-structure-jvm-4.1.jar",
          "size": 145878,
          "sha512": "8406a33c75e5600c921c662bc3028df5f4adeb21194f134e9edfbe1df51d1d4e8b95d325c7c01ef88d4e441c110b2915beb72266e19e4872906a5f8bad6e465e",
          "sha256": "4c968e19b645642cca7285ae57733bebcbd593a51fa32ffb20e1c57778f75140",
          "sha1": "0f1078477a652a27718d4c518a954e99be647ad0",
          "md5": "d46f8c8c6cce8b9fc3be7f77cf487eda"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-jvm-4.1.jar",
          "url": "bb-data-structure-jvm-4.1.jar",
          "size": 145878,
          "sha512": "8406a33c75e5600c921c662bc3028df5f4adeb21194f134e9edfbe1df51d1d4e8b95d325c7c01ef88d4e441c110b2915beb72266e19e4872906a5f8bad6e465e",
          "sha256": "4c968e19b645642cca7285ae57733bebcbd593a51fa32ffb20e1c57778f75140",
          "sha1": "0f1078477a652a27718d4c518a954e99be647ad0",
          "md5": "d46f8c8c6cce8b9fc3be7f77cf487eda"
        }
      ]
    }
  ]
}
