{
  "formatVersion": "1.1",
  "component": {
    "url": "../../uuid-serializer/1.0/uuid-serializer-1.0.module",
    "group": "net.lepinoid",
    "module": "uuid-serializer",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "uuid-serializer-jvm-1.0.jar",
          "url": "uuid-serializer-jvm-1.0.jar",
          "size": 2249,
          "sha512": "c3bbbe7a0af811d401017e445e41bf14b72cc9b8c9d38dd0ee8dcaccc4e246126dff3845aa5755c13e560b8d031ccdab6c0a628d8b464d54f5effdcacd4410d0",
          "sha256": "08dc78f15d422a9d095bdc786be96e824c1dc4ec61c00f92e10057f29498b439",
          "sha1": "0a0db566054840c3dfc6b201f8e4bde6bf46bc36",
          "md5": "c41049a73fdbb936cff9b41256493e0e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "uuid-serializer-jvm-1.0.jar",
          "url": "uuid-serializer-jvm-1.0.jar",
          "size": 2249,
          "sha512": "c3bbbe7a0af811d401017e445e41bf14b72cc9b8c9d38dd0ee8dcaccc4e246126dff3845aa5755c13e560b8d031ccdab6c0a628d8b464d54f5effdcacd4410d0",
          "sha256": "08dc78f15d422a9d095bdc786be96e824c1dc4ec61c00f92e10057f29498b439",
          "sha1": "0a0db566054840c3dfc6b201f8e4bde6bf46bc36",
          "md5": "c41049a73fdbb936cff9b41256493e0e"
        }
      ]
    }
  ]
}
