{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/0.2.0/bb-data-structure-0.2.0.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-jvm-0.2.0.jar",
          "url": "bb-data-structure-jvm-0.2.0.jar",
          "size": 235921,
          "sha512": "2d137de8bd4180160f5eda43e034a69608ac33bea64418e79fc5d52b5674ba88499f6ea363a0cc55699197d4a0283b7859cbc57898da086bb0ed72b822b95126",
          "sha256": "f92e899389183fa53fe6cbf97a57f3b696dcb5b365df9bb39cd3f0256a9c9375",
          "sha1": "e0bbb21fb9ff3a7b7e360a4483fdebf384238d38",
          "md5": "8aa5b2043db8e958a8f299f27723dcde"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-jvm-0.2.0.jar",
          "url": "bb-data-structure-jvm-0.2.0.jar",
          "size": 235921,
          "sha512": "2d137de8bd4180160f5eda43e034a69608ac33bea64418e79fc5d52b5674ba88499f6ea363a0cc55699197d4a0283b7859cbc57898da086bb0ed72b822b95126",
          "sha256": "f92e899389183fa53fe6cbf97a57f3b696dcb5b365df9bb39cd3f0256a9c9375",
          "sha1": "e0bbb21fb9ff3a7b7e360a4483fdebf384238d38",
          "md5": "8aa5b2043db8e958a8f299f27723dcde"
        }
      ]
    }
  ]
}
