{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/0.2.0/bb-data-structure-0.2.0.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-js-0.2.0.klib",
          "url": "bb-data-structure-js-0.2.0.klib",
          "size": 145305,
          "sha512": "ecfd1ed0ef8b1705de3580bd8013b7c89c9fdcd9e2ace79da8330763c454f6b9e298cdc07e676968bd109842997a222cc9bea24b79dcae133d3fab496860d3e2",
          "sha256": "57389e3a5f9bff43fb586634496c2cd931d2281954736d815072c6620ac54af7",
          "sha1": "31e4441c0c4d19e165b8e4410ec7f5a4be578f15",
          "md5": "c6c81b707e69d1434f30c50fab74f181"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-js-0.2.0.klib",
          "url": "bb-data-structure-js-0.2.0.klib",
          "size": 145305,
          "sha512": "ecfd1ed0ef8b1705de3580bd8013b7c89c9fdcd9e2ace79da8330763c454f6b9e298cdc07e676968bd109842997a222cc9bea24b79dcae133d3fab496860d3e2",
          "sha256": "57389e3a5f9bff43fb586634496c2cd931d2281954736d815072c6620ac54af7",
          "sha1": "31e4441c0c4d19e165b8e4410ec7f5a4be578f15",
          "md5": "c6c81b707e69d1434f30c50fab74f181"
        }
      ]
    }
  ]
}
