{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/4.2/bb-data-structure-4.2.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "b7knasy2qrdbpatqkrep6wrkvq"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure.klib",
          "url": "bb-data-structure-native-4.2.klib",
          "size": 102642,
          "sha512": "3f6950b34190552dc9d199b05e0d57f5150c3ca499f8b35e672cb09b9e47173961f4b290eccc24d9a7990cdfe79bd2206e2748b3d303c1d0b3c92168d7762f62",
          "sha256": "a013a1ca1b4e89285c79a10f8be44046272bfb37df158c3f46c5b8cbe8fa0c7c",
          "sha1": "199454ed1b3032b30ecaa55dd6f68600aec30378",
          "md5": "3aaab2a3698bda97d5baa4d0966fcf64"
        }
      ]
    }
  ]
}
