{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-metadata-build.12.jar",
          "url": "model-meta-build.12.jar",
          "size": 4442,
          "sha512": "40f2f263beabc94bf7c27edce111645e8a427fab6ef73ebfab8dbf3ef2f44076e0c0bc7fb28cd9757c1df5b00eabc0aab67edcaf443cc560aeacc2617c32073d",
          "sha256": "a3c2d15c01311fd70b67441cb953b6203972fd709e55306e722c242f004a21dd",
          "sha1": "679d6e9334764caff264a335a2b5be8b1e78a700",
          "md5": "a960107e392faa5611ceaa5fd9aab1ac"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-meta-js/build.12/model-meta-js-build.12.module",
        "group": "net.lepinoid",
        "module": "model-meta-js",
        "version": "build.12"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-meta-js/build.12/model-meta-js-build.12.module",
        "group": "net.lepinoid",
        "module": "model-meta-js",
        "version": "build.12"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-meta-jvm/build.12/model-meta-jvm-build.12.module",
        "group": "net.lepinoid",
        "module": "model-meta-jvm",
        "version": "build.12"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-meta-jvm/build.12/model-meta-jvm-build.12.module",
        "group": "net.lepinoid",
        "module": "model-meta-jvm",
        "version": "build.12"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-meta-native/build.12/model-meta-native-build.12.module",
        "group": "net.lepinoid",
        "module": "model-meta-native",
        "version": "build.12"
      }
    }
  ]
}
