{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/0.1.2/bb-data-structure-0.1.2.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure.klib",
          "url": "bb-data-structure-native-0.1.2.klib",
          "size": 112324,
          "sha512": "12f59c7e15b30eec7cbef6466f389fa1de2a576088c46274c82eaaf00058893ae40d1baead2bdff1b15a99b774bf9568eca5383aad24677cb8960b88c0421539",
          "sha256": "b01193316449b79ba480932a319876864111d36c299d2848b8e0864033a35a81",
          "sha1": "eaabc12665acb90edb60c3372f6070f5cf223aa1",
          "md5": "d4ca7cac3a7f3d79244be016a7d7179d"
        }
      ]
    }
  ]
}
