{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "bbdatastructure",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "564tmoi4crfubd26z5rqx4myme"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-metadata-1.0-all.jar",
          "url": "bbdatastructure-1.0-all.jar",
          "size": 10463,
          "sha512": "5a54c2da3e79fa478b4d73ea810fb6c50f14412575f73a1184910b509802e99c0ef13d0332be7d7da1df5f782620f6973b194dbeb2a316350d4b1c21a48a4205",
          "sha256": "97b179540638eb5ea22ea194dc2ed9c61f9c91433db384d4ed9d2402c6081778",
          "sha1": "473ae7860f3555d4b50a93053c2962556b935b31",
          "md5": "b838a14b60b8067e9e3479133bcce7ff"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-1.0.jar",
          "url": "bbdatastructure-1.0.jar",
          "size": 26611,
          "sha512": "e312b2c69f67ddf9677f91a839e0a9b2f1dc67b453c26c012f6c39a78a8d277486b9dcfe7750cf0fb813ed0530acdb115c8ed74715bcd205cb5f8eba5ce8f49a",
          "sha256": "31ec99d1d57042625cf61825414387ba00ba6efdfb0769d3bafd59e55214db39",
          "sha1": "af26b51b33692f3be13d89ce21b7b7b87cc0ce35",
          "md5": "c02cc61cf03ee8c16c40a2a79e6425ab"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bbdatastructure-js/1.0/bbdatastructure-js-1.0.module",
        "group": "net.lepinoid",
        "module": "bbdatastructure-js",
        "version": "1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bbdatastructure-js/1.0/bbdatastructure-js-1.0.module",
        "group": "net.lepinoid",
        "module": "bbdatastructure-js",
        "version": "1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bbdatastructure-jvm/1.0/bbdatastructure-jvm-1.0.module",
        "group": "net.lepinoid",
        "module": "bbdatastructure-jvm",
        "version": "1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bbdatastructure-jvm/1.0/bbdatastructure-jvm-1.0.module",
        "group": "net.lepinoid",
        "module": "bbdatastructure-jvm",
        "version": "1.0"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bbdatastructure-native/1.0/bbdatastructure-native-1.0.module",
        "group": "net.lepinoid",
        "module": "bbdatastructure-native",
        "version": "1.0"
      }
    }
  ]
}
