{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.19.1+build.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.13.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.13.jar",
          "size": 71382,
          "sha512": "e5eeadf381a860105774482a8a0b62fcec83f9c27274aa230711e550db12ae1e0d55941840e129ee84dd453a7642d6695928e22e45178a395bc35b05ab4c5aad",
          "sha256": "5ef06bae96045cb48f4f1f8690a21d6df37eb97c2f3be664b2beb67819a1197e",
          "sha1": "ef072a058b2185d8a1b798c46f9e82784c8a8d91",
          "md5": "f9592ba5225f6d5b3a0dfddc52ae99ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.19.1+build.13"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.9+e62f51a395"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.5+0c17ea9695"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.1.0+33fbc73895"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.21+23c4cfef95"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.5.6+5f1a85e095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.18+9ff28f4095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.1+3082331495"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.13.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.13.jar",
          "size": 71382,
          "sha512": "e5eeadf381a860105774482a8a0b62fcec83f9c27274aa230711e550db12ae1e0d55941840e129ee84dd453a7642d6695928e22e45178a395bc35b05ab4c5aad",
          "sha256": "5ef06bae96045cb48f4f1f8690a21d6df37eb97c2f3be664b2beb67819a1197e",
          "sha1": "ef072a058b2185d8a1b798c46f9e82784c8a8d91",
          "md5": "f9592ba5225f6d5b3a0dfddc52ae99ae"
        }
      ]
    }
  ]
}
