{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/build.2/bb-data-structure-build.2.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "build.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure.klib",
          "url": "bb-data-structure-native-build.2.klib",
          "size": 147310,
          "sha512": "8dcb20deac10f4af6e908ab976538a1f7732d5d60e57183908b00fb08dc184a1f6b2a35f6be8c24594460fecf8a10354264527b4a124be61ec58bba41e7fe952",
          "sha256": "4b605161d1843958c21b99d54e3e52402fdba251f51595710f2118c201d6a71a",
          "sha1": "872f79b57f7c2172579e61ba8caecbe2649e1482",
          "md5": "efc4e66b852781c2527771c1d335919f"
        }
      ]
    }
  ]
}
