{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.5/model-meta-build.5.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.5.jar",
          "url": "model-meta-jvm-build.5.jar",
          "size": 14264,
          "sha512": "a34a39d09d9406e225a04a1900b5bacf6602ce3d6d7f04dba6351483db34e109a4a7dbbb98c45da04a7f678f44a18e634919a6fe39478e8fc241504e0de6bbc1",
          "sha256": "7afaca23fcb4bea0e532491e1d201849ede83e208de2f5d7f5183c1a2375eef3",
          "sha1": "e639a3856ddfe848d338d4ff960b1b3bef4ed0fe",
          "md5": "25d379dbbee0684cb4badd5207db0b46"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.5.jar",
          "url": "model-meta-jvm-build.5.jar",
          "size": 14264,
          "sha512": "a34a39d09d9406e225a04a1900b5bacf6602ce3d6d7f04dba6351483db34e109a4a7dbbb98c45da04a7f678f44a18e634919a6fe39478e8fc241504e0de6bbc1",
          "sha256": "7afaca23fcb4bea0e532491e1d201849ede83e208de2f5d7f5183c1a2375eef3",
          "sha1": "e639a3856ddfe848d338d4ff960b1b3bef4ed0fe",
          "md5": "25d379dbbee0684cb4badd5207db0b46"
        }
      ]
    }
  ]
}
