{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-protocol",
    "version": "1.19.1+build.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-protocol-1.19.1+build.9.jar",
          "url": "lepinoid-client-protocol-1.19.1+build.9.jar",
          "size": 4932,
          "sha512": "eb9c92d5bef2fcebd982eed7795f4d350698f9a5bee7c64cd3621275f3b9c989f09a5dbdef4e6fb1dee3bec31018f8795d1bf7ede334189666f3267020869f8d",
          "sha256": "8f908c3a128dfd0fb50824b84463e96ea79890a976c6ae72249944dda77238c9",
          "sha1": "6036f69afd304fce65a0bda4fd4acc605e85f3d6",
          "md5": "9e01e9f66319d431e4583d5e53b0bcd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-protocol-1.19.1+build.9.jar",
          "url": "lepinoid-client-protocol-1.19.1+build.9.jar",
          "size": 4932,
          "sha512": "eb9c92d5bef2fcebd982eed7795f4d350698f9a5bee7c64cd3621275f3b9c989f09a5dbdef4e6fb1dee3bec31018f8795d1bf7ede334189666f3267020869f8d",
          "sha256": "8f908c3a128dfd0fb50824b84463e96ea79890a976c6ae72249944dda77238c9",
          "sha1": "6036f69afd304fce65a0bda4fd4acc605e85f3d6",
          "md5": "9e01e9f66319d431e4583d5e53b0bcd6"
        }
      ]
    }
  ]
}
