{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.12/model-meta-build.12.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.12.jar",
          "url": "model-meta-jvm-build.12.jar",
          "size": 19775,
          "sha512": "3180c94faa3959ced92df52be9136acc8e2d99fc774795e167fc2b3faac19e213f18718b0a499ac49f8a87d8d7a94aaddce586632a95a6d32e3404318f09162e",
          "sha256": "7896855d1ff30029e400a4963769f23f40226bbb5bc80a4cb4d1d17e74884f3e",
          "sha1": "433a504b7cb59e21ee81aa386e9ee0c81a05510e",
          "md5": "44519751d2695a705a197c464176b41c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "build.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.12.jar",
          "url": "model-meta-jvm-build.12.jar",
          "size": 19775,
          "sha512": "3180c94faa3959ced92df52be9136acc8e2d99fc774795e167fc2b3faac19e213f18718b0a499ac49f8a87d8d7a94aaddce586632a95a6d32e3404318f09162e",
          "sha256": "7896855d1ff30029e400a4963769f23f40226bbb5bc80a4cb4d1d17e74884f3e",
          "sha1": "433a504b7cb59e21ee81aa386e9ee0c81a05510e",
          "md5": "44519751d2695a705a197c464176b41c"
        }
      ]
    }
  ]
}
