{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.15/model-meta-build.15.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "build.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.15.klib",
          "url": "model-meta-js-build.15.klib",
          "size": 15150,
          "sha512": "44b0841f341416fe9e6b9d9d74f5592b75182ffe2fe6715a7193a108d7a97db162ffa707635838294dd9cc86e31a3f76d6379dbc1b0cdf01512aedc82fe968ba",
          "sha256": "84d91bd0f6f992dac8529ab8f0ee8778b75406c0a70b837571f5a17c3c785976",
          "sha1": "b0af13740b706cdaae981dfdeda159a2fbc366d4",
          "md5": "80f256c8aacc313deb4fa47d3d2111c3"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "build.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.15.klib",
          "url": "model-meta-js-build.15.klib",
          "size": 15150,
          "sha512": "44b0841f341416fe9e6b9d9d74f5592b75182ffe2fe6715a7193a108d7a97db162ffa707635838294dd9cc86e31a3f76d6379dbc1b0cdf01512aedc82fe968ba",
          "sha256": "84d91bd0f6f992dac8529ab8f0ee8778b75406c0a70b837571f5a17c3c785976",
          "sha1": "b0af13740b706cdaae981dfdeda159a2fbc366d4",
          "md5": "80f256c8aacc313deb4fa47d3d2111c3"
        }
      ]
    }
  ]
}
