{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.4/model-meta-build.4.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.4.klib",
          "url": "model-meta-js-build.4.klib",
          "size": 13157,
          "sha512": "c9d3b6f7561a30fb31091da2f252fb45ce17e6455b021dcef44e9a350a3a2858637d976a4df01c87ede6975e69f82d53352f9d9275300290e6f1d7935e4e109b",
          "sha256": "348006cccd5098f256560f62c9c47b4a90a3b11d62dda21c6d41125f5d934ac0",
          "sha1": "08dce970501ba1ef804c35530adc9353803ffafb",
          "md5": "b54ab14fe5ebe8e8dba5d3fe12c7ff88"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.4.klib",
          "url": "model-meta-js-build.4.klib",
          "size": 13157,
          "sha512": "c9d3b6f7561a30fb31091da2f252fb45ce17e6455b021dcef44e9a350a3a2858637d976a4df01c87ede6975e69f82d53352f9d9275300290e6f1d7935e4e109b",
          "sha256": "348006cccd5098f256560f62c9c47b4a90a3b11d62dda21c6d41125f5d934ac0",
          "sha1": "08dce970501ba1ef804c35530adc9353803ffafb",
          "md5": "b54ab14fe5ebe8e8dba5d3fe12c7ff88"
        }
      ]
    }
  ]
}
