{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.2/model-meta-build.2.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.2.jar",
          "url": "model-meta-jvm-build.2.jar",
          "size": 14503,
          "sha512": "52f9f34d6b644ff38977a5ce9d8a8eaf350f8f2b63ad91dc10d285a9e90d17aea6f894a9af1fdd7691c2d2f90e71c2197dbb72e8a8a0469e3d170613b56adb9b",
          "sha256": "b8078f4c5d92b734647094d78b088edcc39ccd95b13476646f9037de9bbbaeab",
          "sha1": "411ce36b1eb3683f885414f4e738f09c8c1e4ce4",
          "md5": "44565a0004e5b4ebc6a3b1070c389054"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.2.jar",
          "url": "model-meta-jvm-build.2.jar",
          "size": 14503,
          "sha512": "52f9f34d6b644ff38977a5ce9d8a8eaf350f8f2b63ad91dc10d285a9e90d17aea6f894a9af1fdd7691c2d2f90e71c2197dbb72e8a8a0469e3d170613b56adb9b",
          "sha256": "b8078f4c5d92b734647094d78b088edcc39ccd95b13476646f9037de9bbbaeab",
          "sha1": "411ce36b1eb3683f885414f4e738f09c8c1e4ce4",
          "md5": "44565a0004e5b4ebc6a3b1070c389054"
        }
      ]
    }
  ]
}
