{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bbdatastructure/1.0/bbdatastructure-1.0.module",
    "group": "net.lepinoid",
    "module": "bbdatastructure",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "564tmoi4crfubd26z5rqx4myme"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-js-1.0.jar",
          "url": "bbdatastructure-js-1.0.jar",
          "size": 34507,
          "sha512": "37df116757d6b1fdacf9dcca27781f99b06ddbc71727fccbf0ff66b67361752671e2dcf8de7ddd318344e5b0ff0ef72d9277e2ca17c7ebf49b884c4031cd3670",
          "sha256": "c82e7b1aa189d33fdc439dca1dea56845c775ee7ca1b8ecd54ce3913607d79fd",
          "sha1": "c85966ea42355ebd858d36db8be7b2eb960d5acd",
          "md5": "d83159d75b430fd84f757e7db2a13229"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-js-1.0.jar",
          "url": "bbdatastructure-js-1.0.jar",
          "size": 34507,
          "sha512": "37df116757d6b1fdacf9dcca27781f99b06ddbc71727fccbf0ff66b67361752671e2dcf8de7ddd318344e5b0ff0ef72d9277e2ca17c7ebf49b884c4031cd3670",
          "sha256": "c82e7b1aa189d33fdc439dca1dea56845c775ee7ca1b8ecd54ce3913607d79fd",
          "sha1": "c85966ea42355ebd858d36db8be7b2eb960d5acd",
          "md5": "d83159d75b430fd84f757e7db2a13229"
        }
      ]
    }
  ]
}
