{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/0.1.2/bb-data-structure-0.1.2.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-js-0.1.2.jar",
          "url": "bb-data-structure-js-0.1.2.jar",
          "size": 50039,
          "sha512": "eef8e51714d7584a20a87932c04055cc864de63d668e549c9bc0092fb5b13d8f8e8914937e397b7ce29d36b9f96d7acd60a8b231ded10c6c491c6725047323d4",
          "sha256": "67cb959c2e25efa2a3adb804fa6ee6e896ad3bd09ac2045cbed55f25fcc4768f",
          "sha1": "3a5881150cea8ada3f4eecb04c8715d814697cc6",
          "md5": "7fcae17486b8bbab16270524c6ebb4ee"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-js-0.1.2.jar",
          "url": "bb-data-structure-js-0.1.2.jar",
          "size": 50039,
          "sha512": "eef8e51714d7584a20a87932c04055cc864de63d668e549c9bc0092fb5b13d8f8e8914937e397b7ce29d36b9f96d7acd60a8b231ded10c6c491c6725047323d4",
          "sha256": "67cb959c2e25efa2a3adb804fa6ee6e896ad3bd09ac2045cbed55f25fcc4768f",
          "sha1": "3a5881150cea8ada3f4eecb04c8715d814697cc6",
          "md5": "7fcae17486b8bbab16270524c6ebb4ee"
        }
      ]
    }
  ]
}
