{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.22/model-meta-build.22.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "build.6"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta.klib",
          "url": "model-meta-native-build.22.klib",
          "size": 17996,
          "sha512": "31fb1fb47d905f3a61c0b67dd4cee60fffa7316ec54a44e689c1274b30ca5d768d21c140387b30000f1980162a6c5625d65263dcd366e9ff91c7d2cb4cd24dfb",
          "sha256": "8245d0e9f20417f272f0b4cd2b5b9966ad75ac5cab0ce64d3429cb15b238c854",
          "sha1": "b97029964ce7948f814eb82ee298cbcf18ae4c14",
          "md5": "e7c6f5d19891ac47e92d15ae5843174b"
        }
      ]
    }
  ]
}
