{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-protocol",
    "version": "1.19+build.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-protocol-1.19+build.1.jar",
          "url": "lepinoid-client-protocol-1.19+build.1.jar",
          "size": 1952,
          "sha512": "54d2028e2f982c05feac4409f3f68fc0adea65b8d148e4dd815eb3e3e5f48b5590f086263eb80777f2cd446bb2e6c45b1c8f7dc4dbb4a1e23a9c5967dbfd8a10",
          "sha256": "6be9524992aeaf93788833ee3309c7176f22c35585dca48d918d7349618c5403",
          "sha1": "abf9761338265e6fb8ef4ac299cdaa854d18b35e",
          "md5": "e895a57ed9681c853a5d65d3c7b3243f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-protocol-1.19+build.1.jar",
          "url": "lepinoid-client-protocol-1.19+build.1.jar",
          "size": 1952,
          "sha512": "54d2028e2f982c05feac4409f3f68fc0adea65b8d148e4dd815eb3e3e5f48b5590f086263eb80777f2cd446bb2e6c45b1c8f7dc4dbb4a1e23a9c5967dbfd8a10",
          "sha256": "6be9524992aeaf93788833ee3309c7176f22c35585dca48d918d7349618c5403",
          "sha1": "abf9761338265e6fb8ef4ac299cdaa854d18b35e",
          "md5": "e895a57ed9681c853a5d65d3c7b3243f"
        }
      ]
    }
  ]
}
