{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.1/model-meta-build.1.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.1.jar",
          "url": "model-meta-jvm-build.1.jar",
          "size": 14264,
          "sha512": "6a17a863a6c4df03d055e5cbd2aeeb35aeb3e5b6023cb070b8a4aa222cf13024b44aaf78131d07e26047b98a94231f51034f4cdcdd99cb1987314147656f3067",
          "sha256": "1a76c49a92f812129c13f3011e6212b63cf49f1c344101d4a7f1e8558b079164",
          "sha1": "9d6a9b06141df8632d59939f52a4d5f06948bc87",
          "md5": "f48bdbd05e1c8adba0e385dbb2e7039e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.1.jar",
          "url": "model-meta-jvm-build.1.jar",
          "size": 14264,
          "sha512": "6a17a863a6c4df03d055e5cbd2aeeb35aeb3e5b6023cb070b8a4aa222cf13024b44aaf78131d07e26047b98a94231f51034f4cdcdd99cb1987314147656f3067",
          "sha256": "1a76c49a92f812129c13f3011e6212b63cf49f1c344101d4a7f1e8558b079164",
          "sha1": "9d6a9b06141df8632d59939f52a4d5f06948bc87",
          "md5": "f48bdbd05e1c8adba0e385dbb2e7039e"
        }
      ]
    }
  ]
}
