{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.1/model-meta-build.1.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.1.jar",
          "url": "model-meta-jvm-build.1.jar",
          "size": 14264,
          "sha512": "1335486fa3632d664eb529f40f469736d33def466ddc3f29aeba87469d96a2c493e43ea45c6f3fbe003458a5de2ea4b5bba8306909ff620c7fc642382fcb0185",
          "sha256": "9ea2ee4744e6643237b8d8adf6105d974ef53735fb6739a2f182b07d54bca87f",
          "sha1": "4cc69c71f5bfc8d369c5d29e32f15e5b840126cf",
          "md5": "b9ace46465a0bb344e74179a1bcca486"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.1.jar",
          "url": "model-meta-jvm-build.1.jar",
          "size": 14264,
          "sha512": "1335486fa3632d664eb529f40f469736d33def466ddc3f29aeba87469d96a2c493e43ea45c6f3fbe003458a5de2ea4b5bba8306909ff620c7fc642382fcb0185",
          "sha256": "9ea2ee4744e6643237b8d8adf6105d974ef53735fb6739a2f182b07d54bca87f",
          "sha1": "4cc69c71f5bfc8d369c5d29e32f15e5b840126cf",
          "md5": "b9ace46465a0bb344e74179a1bcca486"
        }
      ]
    }
  ]
}
