{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.1/model-meta-build.1.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.1.jar",
          "url": "model-meta-jvm-build.1.jar",
          "size": 14264,
          "sha512": "2a7b4ec9fdcd4c4e7a1bc5a3e6049d9690ced032fd099a5bb5bb71f5d44490106267722df2b8d9ef8d9a88caa77339ed829c75c6d7cb1a9bc532eb380c1e8e92",
          "sha256": "5fb428d1fa1f46fda7fbdd4e08861b19d7fef03ab6613e2fe0a7e9e86c8b7226",
          "sha1": "c391fde0e643224cae0b7af0d3cab0a34eef23a0",
          "md5": "95617ed29b4634f714bc4a842dd9b689"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.1.jar",
          "url": "model-meta-jvm-build.1.jar",
          "size": 14264,
          "sha512": "2a7b4ec9fdcd4c4e7a1bc5a3e6049d9690ced032fd099a5bb5bb71f5d44490106267722df2b8d9ef8d9a88caa77339ed829c75c6d7cb1a9bc532eb380c1e8e92",
          "sha256": "5fb428d1fa1f46fda7fbdd4e08861b19d7fef03ab6613e2fe0a7e9e86c8b7226",
          "sha1": "c391fde0e643224cae0b7af0d3cab0a34eef23a0",
          "md5": "95617ed29b4634f714bc4a842dd9b689"
        }
      ]
    }
  ]
}
