{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.1/model-meta-build.1.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.1.klib",
          "url": "model-meta-js-build.1.klib",
          "size": 13157,
          "sha512": "0c45b2371459ebde6af2994cf8ccafc5c61c889ee7669b5d8a689a8c13dd25c2c4a32889d50ae82b444211f6255a05f9db3017dfee989eeb64f5d17fe324191a",
          "sha256": "531da276efb3b4919152e43c8602fb6ff93205ad7e538338327bc04e49831d65",
          "sha1": "55ee6932c7162a15e0e2a03cdc080abe746cf31f",
          "md5": "4c02388a4b11cd15ad5e6ff9e93fb65f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.1.klib",
          "url": "model-meta-js-build.1.klib",
          "size": 13157,
          "sha512": "0c45b2371459ebde6af2994cf8ccafc5c61c889ee7669b5d8a689a8c13dd25c2c4a32889d50ae82b444211f6255a05f9db3017dfee989eeb64f5d17fe324191a",
          "sha256": "531da276efb3b4919152e43c8602fb6ff93205ad7e538338327bc04e49831d65",
          "sha1": "55ee6932c7162a15e0e2a03cdc080abe746cf31f",
          "md5": "4c02388a4b11cd15ad5e6ff9e93fb65f"
        }
      ]
    }
  ]
}
