{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.1/model-meta-build.1.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.1.klib",
          "url": "model-meta-js-build.1.klib",
          "size": 13155,
          "sha512": "964d4fc35e9dd54ca7d1eb360b6dc0153ba6883eb5af175d5c276b52a42f2bccb45340e07181ce647e6870b1987cfdd8736f26e7b3d1a3e47453f95d89f93e3a",
          "sha256": "d577c07182ea32337a6392f11dd9e07571e60522e8b0b20cd0c6592848748e9d",
          "sha1": "8bc40f2613cddc96dbdddaeee113d65da98537a9",
          "md5": "7cf28b28db3d057caefcdd919033b617"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.1.klib",
          "url": "model-meta-js-build.1.klib",
          "size": 13155,
          "sha512": "964d4fc35e9dd54ca7d1eb360b6dc0153ba6883eb5af175d5c276b52a42f2bccb45340e07181ce647e6870b1987cfdd8736f26e7b3d1a3e47453f95d89f93e3a",
          "sha256": "d577c07182ea32337a6392f11dd9e07571e60522e8b0b20cd0c6592848748e9d",
          "sha1": "8bc40f2613cddc96dbdddaeee113d65da98537a9",
          "md5": "7cf28b28db3d057caefcdd919033b617"
        }
      ]
    }
  ]
}
