{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/build.30/bb-data-structure-build.30.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "build.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-js-build.30.klib",
          "url": "bb-data-structure-js-build.30.klib",
          "size": 195206,
          "sha512": "4ca6bfa58cbad9d42fda781a64c76e4a9b96cb390308c4b87ee1468a38a4234ae464793c1eca2f679185333c30f2c25f0a5e2c7a785cf9e37859dbdd4c760181",
          "sha256": "fd565e4445ab5773e166a6229587502059c59d74b8f9ab655ae746d12d07f443",
          "sha1": "b8100fc47cef5d1698a19ab47d46c4de8389beb8",
          "md5": "701684f585be9873eda8bcf7c517da35"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-js-build.30.klib",
          "url": "bb-data-structure-js-build.30.klib",
          "size": 195206,
          "sha512": "4ca6bfa58cbad9d42fda781a64c76e4a9b96cb390308c4b87ee1468a38a4234ae464793c1eca2f679185333c30f2c25f0a5e2c7a785cf9e37859dbdd4c760181",
          "sha256": "fd565e4445ab5773e166a6229587502059c59d74b8f9ab655ae746d12d07f443",
          "sha1": "b8100fc47cef5d1698a19ab47d46c4de8389beb8",
          "md5": "701684f585be9873eda8bcf7c517da35"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "bb-data-structure-js-build.30-sources.jar",
          "url": "bb-data-structure-js-build.30-sources.jar",
          "size": 15940,
          "sha512": "bf3fcc9722e2542da2b8a91b52bc86dd09d3c98a31d7af3a941eb3c1aa78a20e5babd866f0de347983f8b77a5f2c2fdf6baf482e73c364bb0d4b1341f7c1664e",
          "sha256": "504d5593bc3e1405dfb042bd233fbc95e24339e7ea5585c5171395d2f5f3fdba",
          "sha1": "a41cabdd3822425292ef1881a3dac0d800d2ddf1",
          "md5": "dacc82048b2d2df33ce438e38c7e2cc1"
        }
      ]
    }
  ]
}
