{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-protocol",
    "version": "1.19.1+build.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-protocol-1.19.1+build.10.jar",
          "url": "lepinoid-client-protocol-1.19.1+build.10.jar",
          "size": 4932,
          "sha512": "41c86a87d8bff6a57f12eab9c7cb8dfc610024562949a6226302642cc3579b19d6f83e3b81c4b9cc527280ddd40accccaf7deeaf9e09e31741d6149e9fd6b842",
          "sha256": "a43ae3cd386ca88689967882dc4fc998aeba146aa36247033405d1e9785df6cc",
          "sha1": "e9711bac1d51db2342c842ac5ee25c5bd085130f",
          "md5": "de04b1c839817177409895d13cd4283a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-protocol-1.19.1+build.10.jar",
          "url": "lepinoid-client-protocol-1.19.1+build.10.jar",
          "size": 4932,
          "sha512": "41c86a87d8bff6a57f12eab9c7cb8dfc610024562949a6226302642cc3579b19d6f83e3b81c4b9cc527280ddd40accccaf7deeaf9e09e31741d6149e9fd6b842",
          "sha256": "a43ae3cd386ca88689967882dc4fc998aeba146aa36247033405d1e9785df6cc",
          "sha1": "e9711bac1d51db2342c842ac5ee25c5bd085130f",
          "md5": "de04b1c839817177409895d13cd4283a"
        }
      ]
    }
  ]
}
