{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.19.1+build.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.1.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.1.jar",
          "size": 25624,
          "sha512": "1cb908b99ede25124af05d8b941fd108c333332e19844e38411dbc45f19b400ff7ea5ea03a48a07a98525299d382e3e75c9f781fdd5a6e016ceb8ac7d22b5428",
          "sha256": "ed977af9ee32fd4f9ef5b74370e0bc808d61c805e57509b1430bc04842ca5209",
          "sha1": "3603ec94bc662fcba55959fed5e74f7d1681fb4c",
          "md5": "c9e8f5b9d226867850a945e2850bf660"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.19.1+build.1"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.9+e62f51a395"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.5+0c17ea9695"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.1.0+33fbc73895"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.21+23c4cfef95"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.5.6+5f1a85e095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.18+9ff28f4095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.1+3082331495"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.1.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.1.jar",
          "size": 25624,
          "sha512": "1cb908b99ede25124af05d8b941fd108c333332e19844e38411dbc45f19b400ff7ea5ea03a48a07a98525299d382e3e75c9f781fdd5a6e016ceb8ac7d22b5428",
          "sha256": "ed977af9ee32fd4f9ef5b74370e0bc808d61c805e57509b1430bc04842ca5209",
          "sha1": "3603ec94bc662fcba55959fed5e74f7d1681fb4c",
          "md5": "c9e8f5b9d226867850a945e2850bf660"
        }
      ]
    }
  ]
}
