{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/4.1/bb-data-structure-4.1.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "rsrlcfmwznhinfyhocpav4nvdq"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure.klib",
          "url": "bb-data-structure-native-4.1.klib",
          "size": 100515,
          "sha512": "5d048fe1bd28795938f01968dfcb3d87c07436d32784922185700d3dba6f40ce1c2260dc265526635468e13a273add59e96e23d3c02734c822d9462b59bcc944",
          "sha256": "65d10526e1bdd438754aa0af436a03217b9451fee5a550266c88b3a9355de6db",
          "sha1": "3496c0668c83c2096595711c970ed53f7468ed50",
          "md5": "a24dc18f73f34d177723be68724a3aae"
        }
      ]
    }
  ]
}
