{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-protocol",
    "version": "1.19+build.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-protocol-1.19+build.2.jar",
          "url": "lepinoid-client-protocol-1.19+build.2.jar",
          "size": 1954,
          "sha512": "be72580e3bb0be0679b2a5a601ea2b33e411f32bbcda2ef03b34cd9ff54565dff8ca15c86e993ccebf4c58fdc44914ed4cb29ef14cfbd26c395abf5ca4e7731b",
          "sha256": "f90f52382d97135f154223533973906d12accc5d0b2fd9d70d97f82858bad878",
          "sha1": "522ca7c55c5a07c28bc33be1b55ba2cbd603c1ae",
          "md5": "599c8534a5ccaf604157ab9b4d6e1f5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-protocol-1.19+build.2.jar",
          "url": "lepinoid-client-protocol-1.19+build.2.jar",
          "size": 1954,
          "sha512": "be72580e3bb0be0679b2a5a601ea2b33e411f32bbcda2ef03b34cd9ff54565dff8ca15c86e993ccebf4c58fdc44914ed4cb29ef14cfbd26c395abf5ca4e7731b",
          "sha256": "f90f52382d97135f154223533973906d12accc5d0b2fd9d70d97f82858bad878",
          "sha1": "522ca7c55c5a07c28bc33be1b55ba2cbd603c1ae",
          "md5": "599c8534a5ccaf604157ab9b4d6e1f5b"
        }
      ]
    }
  ]
}
