{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/0.1.2/bb-data-structure-0.1.2.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-jvm-0.1.2.jar",
          "url": "bb-data-structure-jvm-0.1.2.jar",
          "size": 169823,
          "sha512": "0c5c73dd706e43a5da35e754bc00daab3c36bf26a127f6a2ab08759a9b20210c8922718cb472419d6fbebf711ac51945e0a68cbf5a5ca06fd4bae1cb6ef13348",
          "sha256": "a4291ba230021101ab3cafb508d536df03cb22e4cf068250f40826a5d74c6b56",
          "sha1": "8cc9c7b1810b7b4928a0b2333093fc1a8dc77cef",
          "md5": "93a254aebca1741db59b4da170e4eb61"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-jvm-0.1.2.jar",
          "url": "bb-data-structure-jvm-0.1.2.jar",
          "size": 169823,
          "sha512": "0c5c73dd706e43a5da35e754bc00daab3c36bf26a127f6a2ab08759a9b20210c8922718cb472419d6fbebf711ac51945e0a68cbf5a5ca06fd4bae1cb6ef13348",
          "sha256": "a4291ba230021101ab3cafb508d536df03cb22e4cf068250f40826a5d74c6b56",
          "sha1": "8cc9c7b1810b7b4928a0b2333093fc1a8dc77cef",
          "md5": "93a254aebca1741db59b4da170e4eb61"
        }
      ]
    }
  ]
}
