{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.19.1+build.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.2.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.2.jar",
          "size": 28039,
          "sha512": "467c9a79cb88bc699e74430600b7bf01b1171722e22a6082be3c4f67b85602c63b78589ee579035b361d38f41430976a41da4b5f953fbcaf0be17b96ee4b87ab",
          "sha256": "0bfeaac4f80b4874044d5674e366bc6b2dfadc39f3f4492b62e80b6cb8356494",
          "sha1": "3529109fab613dbb332bc0cfd67cc701b6521314",
          "md5": "dc9ccd9c0c37130478ebbcb6049e8ca2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.19.1+build.2"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.9+e62f51a395"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.5+0c17ea9695"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.1.0+33fbc73895"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.21+23c4cfef95"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.5.6+5f1a85e095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.18+9ff28f4095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.1+3082331495"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.2.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.2.jar",
          "size": 28039,
          "sha512": "467c9a79cb88bc699e74430600b7bf01b1171722e22a6082be3c4f67b85602c63b78589ee579035b361d38f41430976a41da4b5f953fbcaf0be17b96ee4b87ab",
          "sha256": "0bfeaac4f80b4874044d5674e366bc6b2dfadc39f3f4492b62e80b6cb8356494",
          "sha1": "3529109fab613dbb332bc0cfd67cc701b6521314",
          "md5": "dc9ccd9c0c37130478ebbcb6049e8ca2"
        }
      ]
    }
  ]
}
