{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.4/model-meta-build.4.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.4.jar",
          "url": "model-meta-jvm-build.4.jar",
          "size": 14264,
          "sha512": "4d990a7b15289a7415f92db1f01e16dd64689d6e3a252653ef6de58832700edf42237d3f629e69e3918461a400f2cef9021dec0c684f5614637713be43a7e426",
          "sha256": "913350bdc3620daee42efffceecd1f9ac010c84b7c95cb6d9569685c76b055b3",
          "sha1": "3004853f229ddf4d355d14cb2c9531ced0e0f667",
          "md5": "d8cc0594f281136ecd52c4d184e6eff3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.4.jar",
          "url": "model-meta-jvm-build.4.jar",
          "size": 14264,
          "sha512": "4d990a7b15289a7415f92db1f01e16dd64689d6e3a252653ef6de58832700edf42237d3f629e69e3918461a400f2cef9021dec0c684f5614637713be43a7e426",
          "sha256": "913350bdc3620daee42efffceecd1f9ac010c84b7c95cb6d9569685c76b055b3",
          "sha1": "3004853f229ddf4d355d14cb2c9531ced0e0f667",
          "md5": "d8cc0594f281136ecd52c4d184e6eff3"
        }
      ]
    }
  ]
}
