{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.29/model-meta-build.29.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.29.klib",
          "url": "model-meta-js-build.29.klib",
          "size": 17755,
          "sha512": "50f3d0f1b22e45f526afa7b5536eae5e2ce91b3d8f7025b146c1d7ea2899c937a61257b124e6330662af97494662f8341ee339e3165bce5b6e91c35603067f64",
          "sha256": "a7f78fb441e0ce0ea7cd2e59ada9b2e645b1cda70fe48db53220a325a2a713d1",
          "sha1": "008a3fc6ee0117c613ff501b6956f461214b149e",
          "md5": "30018ceab6b1966dc2778e7a84fd415b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "build.24"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.29.klib",
          "url": "model-meta-js-build.29.klib",
          "size": 17755,
          "sha512": "50f3d0f1b22e45f526afa7b5536eae5e2ce91b3d8f7025b146c1d7ea2899c937a61257b124e6330662af97494662f8341ee339e3165bce5b6e91c35603067f64",
          "sha256": "a7f78fb441e0ce0ea7cd2e59ada9b2e645b1cda70fe48db53220a325a2a713d1",
          "sha1": "008a3fc6ee0117c613ff501b6956f461214b149e",
          "md5": "30018ceab6b1966dc2778e7a84fd415b"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "model-meta-js-build.29-sources.jar",
          "url": "model-meta-js-build.29-sources.jar",
          "size": 1056,
          "sha512": "23a3302c46dcac55a9f7e8b79bd4fd2bf8e3c3a334c2b8d80900363242aacbab979abbfb68225adc18fa3a72bbcac998cb2da2831acb989e790da4913965ade8",
          "sha256": "695be92ff69a8c77161f44f8dde0fc0b9e53fa5179fe8e8e95fff65a0c561532",
          "sha1": "a80c62218de71f380ffa5ed56ab71c894a905184",
          "md5": "92f497249536faaf692eafc223da5578"
        }
      ]
    }
  ]
}
