{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.19.1+build.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.6.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.6.jar",
          "size": 58590,
          "sha512": "fbb690f8129fb3cc62894ea3e496849d3c5c3a6ebf163cc3f3aee1425b559c8508b8838b279be784d263c948f0d4fa52467ef386c44a4f659bd8e4021b533410",
          "sha256": "7f15b862f4ed7d98cfdca5071594eedce2e51cc57cdbc10e6861898216fee0fb",
          "sha1": "63036c48e740042b321c22489875888a10b4a91d",
          "md5": "293180d40302cd410d3b29e6d75aeac7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.19.1+build.6"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.9+e62f51a395"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.5+0c17ea9695"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.1.0+33fbc73895"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.21+23c4cfef95"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.5.6+5f1a85e095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.18+9ff28f4095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.1+3082331495"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.6.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.6.jar",
          "size": 58590,
          "sha512": "fbb690f8129fb3cc62894ea3e496849d3c5c3a6ebf163cc3f3aee1425b559c8508b8838b279be784d263c948f0d4fa52467ef386c44a4f659bd8e4021b533410",
          "sha256": "7f15b862f4ed7d98cfdca5071594eedce2e51cc57cdbc10e6861898216fee0fb",
          "sha1": "63036c48e740042b321c22489875888a10b4a91d",
          "md5": "293180d40302cd410d3b29e6d75aeac7"
        }
      ]
    }
  ]
}
