{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.19.1+build.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.3.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.3.jar",
          "size": 32822,
          "sha512": "edb75334abb76ac64ddb48b23b163a9ef1361c50de6695ebdd5e308a25d088645539185428edb00867d055d006ae696e183d8cdd0d6cff3f8731ee731b21ba03",
          "sha256": "6309583a0e2aa751b83dadc4ebab5d86e0abdbea5c298e8487c7da38053429af",
          "sha1": "9e172ef956d95539c0ea24dfe7c7c5240d49b67d",
          "md5": "37ce59a1806b746e906337b065a0a8f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.19.1+build.3"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.9+e62f51a395"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.5+0c17ea9695"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.1.0+33fbc73895"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.21+23c4cfef95"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.5.6+5f1a85e095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.18+9ff28f4095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.1+3082331495"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.3.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.3.jar",
          "size": 32822,
          "sha512": "edb75334abb76ac64ddb48b23b163a9ef1361c50de6695ebdd5e308a25d088645539185428edb00867d055d006ae696e183d8cdd0d6cff3f8731ee731b21ba03",
          "sha256": "6309583a0e2aa751b83dadc4ebab5d86e0abdbea5c298e8487c7da38053429af",
          "sha1": "9e172ef956d95539c0ea24dfe7c7c5240d49b67d",
          "md5": "37ce59a1806b746e906337b065a0a8f3"
        }
      ]
    }
  ]
}
