{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.19.1+build.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.8.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.8.jar",
          "size": 58747,
          "sha512": "fb921ae7ef16923dd3f6c0e0910693960c6d089540aa52bfdd4fefba0f29d0ffa98ad373cd6dd0fd1ea05566770176419f4aa1480e180d35b166d2df89656c4b",
          "sha256": "a03d0b453b4ca9d2a97c809b21b9ef3058395d6b54c697b011ca73e345a676d3",
          "sha1": "35b285c61450af02b098738f9d62670fe94f5bfa",
          "md5": "d14ad7d812b80317aee4a82c45cd9afb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.19.1+build.8"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.9+e62f51a395"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.5+0c17ea9695"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.1.0+33fbc73895"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.21+23c4cfef95"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.5.6+5f1a85e095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.18+9ff28f4095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.1+3082331495"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.8.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.8.jar",
          "size": 58747,
          "sha512": "fb921ae7ef16923dd3f6c0e0910693960c6d089540aa52bfdd4fefba0f29d0ffa98ad373cd6dd0fd1ea05566770176419f4aa1480e180d35b166d2df89656c4b",
          "sha256": "a03d0b453b4ca9d2a97c809b21b9ef3058395d6b54c697b011ca73e345a676d3",
          "sha1": "35b285c61450af02b098738f9d62670fe94f5bfa",
          "md5": "d14ad7d812b80317aee4a82c45cd9afb"
        }
      ]
    }
  ]
}
