{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.16/model-meta-build.16.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.16.jar",
          "url": "model-meta-jvm-build.16.jar",
          "size": 19775,
          "sha512": "29f44c64789b48675043b872eff087b0b2fb8ed03826fd313e075887cc4ca1d4bc1156ebe6979b3df0a03cca1ac3dad879aabb4329e530972483abe1a87a91c8",
          "sha256": "d8d9c68e6fe42ca7018acb79b31d4421876deb138e2d6ae095c8f71d3b2ea1f8",
          "sha1": "5d000a51562e0298cf4d7d7023c64a6cf404759f",
          "md5": "9236dd97b1c032b993d24b2ac27cbf38"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "build.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.16.jar",
          "url": "model-meta-jvm-build.16.jar",
          "size": 19775,
          "sha512": "29f44c64789b48675043b872eff087b0b2fb8ed03826fd313e075887cc4ca1d4bc1156ebe6979b3df0a03cca1ac3dad879aabb4329e530972483abe1a87a91c8",
          "sha256": "d8d9c68e6fe42ca7018acb79b31d4421876deb138e2d6ae095c8f71d3b2ea1f8",
          "sha1": "5d000a51562e0298cf4d7d7023c64a6cf404759f",
          "md5": "9236dd97b1c032b993d24b2ac27cbf38"
        }
      ]
    }
  ]
}
