{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-protocol",
    "version": "1.19.1+build.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-protocol-1.19.1+build.5.jar",
          "url": "lepinoid-client-protocol-1.19.1+build.5.jar",
          "size": 4932,
          "sha512": "cb58edcca17cedb9d5d678569ab69ce7d03b12af487f7bb819be9d96aa0daa9e2f80a9c9cc4a86cbcd490c021628378b84a3f8160e55d7eeec297485968c8d2a",
          "sha256": "d6ab8f5e2700f6c3c5b44be1e541a461099fd9c11bbac048346c923ebf14d04e",
          "sha1": "b5b6203f37a0a9d2097afc597a29d785a9b48c6a",
          "md5": "c5a3ac87138405ce644d41d05f9c141a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-protocol-1.19.1+build.5.jar",
          "url": "lepinoid-client-protocol-1.19.1+build.5.jar",
          "size": 4932,
          "sha512": "cb58edcca17cedb9d5d678569ab69ce7d03b12af487f7bb819be9d96aa0daa9e2f80a9c9cc4a86cbcd490c021628378b84a3f8160e55d7eeec297485968c8d2a",
          "sha256": "d6ab8f5e2700f6c3c5b44be1e541a461099fd9c11bbac048346c923ebf14d04e",
          "sha1": "b5b6203f37a0a9d2097afc597a29d785a9b48c6a",
          "md5": "c5a3ac87138405ce644d41d05f9c141a"
        }
      ]
    }
  ]
}
