{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "build.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-metadata-build.6.jar",
          "url": "bb-data-structure-build.6.jar",
          "size": 16503,
          "sha512": "1baaaa4c088a286c24a22bfb6a1e22bc8a9172a3a0bf8d1c3d2bf88fac2e4693d5f622a7d8eab97dd0e654c17fdcc96d20de8e105ee3194c5bf385f671eaf7ed",
          "sha256": "5598ec080db5553e0edf26e047ab2eeb94bac2f2d1b1068f7f9a5df8d6c7e4b1",
          "sha1": "98c3afff18b14026ad0bbda4595dcd1396baa772",
          "md5": "ecea7a53cb6d4b738bc131e2dca9e21d"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/build.6/bb-data-structure-js-build.6.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "build.6"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/build.6/bb-data-structure-js-build.6.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "build.6"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/build.6/bb-data-structure-jvm-build.6.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "build.6"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/build.6/bb-data-structure-jvm-build.6.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "build.6"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bb-data-structure-native/build.6/bb-data-structure-native-build.6.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-native",
        "version": "build.6"
      }
    }
  ]
}
