{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "ad2xan7egncchcoogl6c4acjpi"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-metadata-4.0-all.jar",
          "url": "bb-data-structure-4.0-all.jar",
          "size": 10734,
          "sha512": "db124c97d97c7e0a5d6659f384fd6db3b4df82613f5d413f7910da1568aaea6d7e862c390948900dfb908c1eddbae7b19b9833411910bac762cd9902faf0eab7",
          "sha256": "684d1c87f2d70bb6d07029401c5b4cbc03d490a4b03302a52d4e2913462b2faa",
          "sha1": "908b653c57716b9db3fbf08d98f689c8f33432ba",
          "md5": "44d1714182d1e193faac56eeed6efea8"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-4.0.jar",
          "url": "bb-data-structure-4.0.jar",
          "size": 27069,
          "sha512": "7b4a9748977cd8b3253f0d19893a33e4acc26fc8d6969fc4c63c5217832c847d8e0eddbb2d5f9df888f298928203dd8d793094348452898c3582497af74ab7bf",
          "sha256": "385b327cbfde23f674454eb1777f36c24bc27b17a1229b6ed42ee52b104e7019",
          "sha1": "45dfb384d9696aa41272eadb9d822f6d815a95d9",
          "md5": "baebff7149ae2e7cd03b37d0c3cff8eb"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/4.0/bb-data-structure-js-4.0.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "4.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../bb-data-structure-js/4.0/bb-data-structure-js-4.0.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-js",
        "version": "4.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/4.0/bb-data-structure-jvm-4.0.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "4.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../bb-data-structure-jvm/4.0/bb-data-structure-jvm-4.0.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-jvm",
        "version": "4.0"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../bb-data-structure-native/4.0/bb-data-structure-native-4.0.module",
        "group": "net.lepinoid",
        "module": "bb-data-structure-native",
        "version": "4.0"
      }
    }
  ]
}
