{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.5/model-meta-build.5.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.5.klib",
          "url": "model-meta-js-build.5.klib",
          "size": 13158,
          "sha512": "2beb1e6e77ec8fbd0b71f5eefb15addc3988b75b9833b2c263919cb0a43cc3f6bc7aa3898dcc9b004e70a4171bff91706892e0930a8b747c9524d05c9df0765b",
          "sha256": "f7ec217ab2f37e5771d1e40c35856bb3758b0513fe260cb8abdb6e7daa5c33c4",
          "sha1": "8a9962384fdabaadc2e44225e8a5aa2e2e139ae8",
          "md5": "06c82fae2b2a053058341ca1f06996ba"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.5.klib",
          "url": "model-meta-js-build.5.klib",
          "size": 13158,
          "sha512": "2beb1e6e77ec8fbd0b71f5eefb15addc3988b75b9833b2c263919cb0a43cc3f6bc7aa3898dcc9b004e70a4171bff91706892e0930a8b747c9524d05c9df0765b",
          "sha256": "f7ec217ab2f37e5771d1e40c35856bb3758b0513fe260cb8abdb6e7daa5c33c4",
          "sha1": "8a9962384fdabaadc2e44225e8a5aa2e2e139ae8",
          "md5": "06c82fae2b2a053058341ca1f06996ba"
        }
      ]
    }
  ]
}
