{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.2/model-meta-build.2.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.2.klib",
          "url": "model-meta-js-build.2.klib",
          "size": 13467,
          "sha512": "4905eef8f947f4614ab945671c7ae0d3ae02771cdeb2ef114d2689258feabf08776b9f7e9d998bbf0e5d6a01a841d68fe1bdde17c24d46398bf4807713670fcb",
          "sha256": "faf129116e85962a7db46b1241a7fdd6c7f13852ef0ebd7ea635aeb64c5a3bbc",
          "sha1": "63d619d5dd899184a0e1459f3fc8983cbbe33f08",
          "md5": "b23940957e6367386f8a2628b4344e9e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-js-build.2.klib",
          "url": "model-meta-js-build.2.klib",
          "size": 13467,
          "sha512": "4905eef8f947f4614ab945671c7ae0d3ae02771cdeb2ef114d2689258feabf08776b9f7e9d998bbf0e5d6a01a841d68fe1bdde17c24d46398bf4807713670fcb",
          "sha256": "faf129116e85962a7db46b1241a7fdd6c7f13852ef0ebd7ea635aeb64c5a3bbc",
          "sha1": "63d619d5dd899184a0e1459f3fc8983cbbe33f08",
          "md5": "b23940957e6367386f8a2628b4344e9e"
        }
      ]
    }
  ]
}
