{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/0.2.1/bb-data-structure-0.2.1.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-jvm-0.2.1.jar",
          "url": "bb-data-structure-jvm-0.2.1.jar",
          "size": 235956,
          "sha512": "36cdf9be7e8f608bdcb57d468d68dce76b60761e9354a22e0ab1e8a31df112d6e931846559e9aa013e95b508f15361d4de96876b0dcbdfe289cef15f395baf9d",
          "sha256": "efa65b0d150cc3439a68b1be32a95403a00b9819f021dfd5b7dc654a0f9e5a30",
          "sha1": "a18eb19aeae1aa5e74ba9b9f0c074d8e7f54a266",
          "md5": "a1f09872985bb022974e8217536ecb5a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-jvm-0.2.1.jar",
          "url": "bb-data-structure-jvm-0.2.1.jar",
          "size": 235956,
          "sha512": "36cdf9be7e8f608bdcb57d468d68dce76b60761e9354a22e0ab1e8a31df112d6e931846559e9aa013e95b508f15361d4de96876b0dcbdfe289cef15f395baf9d",
          "sha256": "efa65b0d150cc3439a68b1be32a95403a00b9819f021dfd5b7dc654a0f9e5a30",
          "sha1": "a18eb19aeae1aa5e74ba9b9f0c074d8e7f54a266",
          "md5": "a1f09872985bb022974e8217536ecb5a"
        }
      ]
    }
  ]
}
