{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.19+build.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19+build.2.jar",
          "url": "lepinoid-client-fabric-1.19+build.2.jar",
          "size": 28032,
          "sha512": "61a3ec2c9c513e635c547d3eac9938b71d00fda02e20fcb516fa662e21ac8b445e6423086745322690edff5c8d5759a66c45de015c0224b1e7d5c7f0a2699132",
          "sha256": "a4204cbead1fd1a465a93e4017c02bc96a7a1bbb7bf8e0ac518597926eb98e97",
          "sha1": "fefcccc93b92c2c5f02896a9741d17a68ff44ca6",
          "md5": "e4e3edb2d3137512a1476deaadb57421"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.19+build.2"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.9+e62f51a395"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.5+0c17ea9695"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.1.0+33fbc73895"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.21+23c4cfef95"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.5.6+5f1a85e095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.18+9ff28f4095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.1+3082331495"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19+build.2.jar",
          "url": "lepinoid-client-fabric-1.19+build.2.jar",
          "size": 28032,
          "sha512": "61a3ec2c9c513e635c547d3eac9938b71d00fda02e20fcb516fa662e21ac8b445e6423086745322690edff5c8d5759a66c45de015c0224b1e7d5c7f0a2699132",
          "sha256": "a4204cbead1fd1a465a93e4017c02bc96a7a1bbb7bf8e0ac518597926eb98e97",
          "sha1": "fefcccc93b92c2c5f02896a9741d17a68ff44ca6",
          "md5": "e4e3edb2d3137512a1476deaadb57421"
        }
      ]
    }
  ]
}
