{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bbdatastructure/1.0/bbdatastructure-1.0.module",
    "group": "net.lepinoid",
    "module": "bbdatastructure",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "564tmoi4crfubd26z5rqx4myme"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-jvm-1.0.jar",
          "url": "bbdatastructure-jvm-1.0.jar",
          "size": 136763,
          "sha512": "03a51b157efd825ac69d71262c065cdca6ab3226fc05ab2acba7499ef9d9e298917477af7650e5a3dbfa15e5b7d50925c3226b93a8bcde6202d54670824aaf17",
          "sha256": "a35b663b99d3bbb36e548a9212a1c1f5dbed79e0d3d90d6a4e4baacb213f186f",
          "sha1": "e06f4a62b7250cedecb42377f7f252f6d441402c",
          "md5": "deb0b5a5075004761d49648b67c14ea3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-jvm-1.0.jar",
          "url": "bbdatastructure-jvm-1.0.jar",
          "size": 136763,
          "sha512": "03a51b157efd825ac69d71262c065cdca6ab3226fc05ab2acba7499ef9d9e298917477af7650e5a3dbfa15e5b7d50925c3226b93a8bcde6202d54670824aaf17",
          "sha256": "a35b663b99d3bbb36e548a9212a1c1f5dbed79e0d3d90d6a4e4baacb213f186f",
          "sha1": "e06f4a62b7250cedecb42377f7f252f6d441402c",
          "md5": "deb0b5a5075004761d49648b67c14ea3"
        }
      ]
    }
  ]
}
