{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bb-data-structure/0.1.1/bb-data-structure-0.1.1.module",
    "group": "net.lepinoid",
    "module": "bb-data-structure",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "tjdrkytcpredjbhpqbkllzzvc4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-jvm-0.1.1.jar",
          "url": "bb-data-structure-jvm-0.1.1.jar",
          "size": 168680,
          "sha512": "993cdadddd7803a8660072dc66ca74398560b0f148aa88ef48a3978eec5903e62fcc84b7b1b5833d525ef6ed4176aceda3ab7632d9fff491abcda4584d8889e7",
          "sha256": "734752b17f1f937ecd8cc999184fd599099372108336a2cf8eb339906df1c2f2",
          "sha1": "097a896012c7da3b633bbda9242314d33aa42f0d",
          "md5": "a42a0c7d5d3476edee8e8a8f7cbfa344"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "bb-data-structure-jvm-0.1.1.jar",
          "url": "bb-data-structure-jvm-0.1.1.jar",
          "size": 168680,
          "sha512": "993cdadddd7803a8660072dc66ca74398560b0f148aa88ef48a3978eec5903e62fcc84b7b1b5833d525ef6ed4176aceda3ab7632d9fff491abcda4584d8889e7",
          "sha256": "734752b17f1f937ecd8cc999184fd599099372108336a2cf8eb339906df1c2f2",
          "sha1": "097a896012c7da3b633bbda9242314d33aa42f0d",
          "md5": "a42a0c7d5d3476edee8e8a8f7cbfa344"
        }
      ]
    }
  ]
}
