{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.2/model-meta-build.2.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta.klib",
          "url": "model-meta-native-build.2.klib",
          "size": 15785,
          "sha512": "cbb40602bd56ed507a2894575527dc48e0cb38cb6901520c8115b8f5c3f310b3dcdd0c1ff0a37a515d2227e68c2663fd2e95f73e4a31c4205d3ecda23e0bec4a",
          "sha256": "72c543d40304d51b6742041dc531144b666eba37838dd7287c25b2ec4440bb3e",
          "sha1": "68ac8eb68aa110c37a604383323fde4b417383fe",
          "md5": "6d24ffd090a0d1b9891efcf4b0dfcae9"
        }
      ]
    }
  ]
}
