{
  "formatVersion": "1.1",
  "component": {
    "url": "../../bbdatastructure/2.0/bbdatastructure-2.0.module",
    "group": "net.lepinoid",
    "module": "bbdatastructure",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "hshakwshxbfalagj2je7ygwa5u"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-js-2.0.jar",
          "url": "bbdatastructure-js-2.0.jar",
          "size": 34507,
          "sha512": "b237b2b9a37fe36160b800612da598f80caba0c1eea39a55aa4a68f5566bc13957c5392d0e0aa681038fd0f04ea3989a2970b883839429d0130ed08f620a1db2",
          "sha256": "01e8ceebcbd993deb0643fb42db6c78e7553bfd1d60c23abf7fa4161dda1f467",
          "sha1": "6a2ec0ed60295320ea4039402fad1b73ad13d678",
          "md5": "e052287c6a2cfe6b8d0d94718785a0fa"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "bbdatastructure-js-2.0.jar",
          "url": "bbdatastructure-js-2.0.jar",
          "size": 34507,
          "sha512": "b237b2b9a37fe36160b800612da598f80caba0c1eea39a55aa4a68f5566bc13957c5392d0e0aa681038fd0f04ea3989a2970b883839429d0130ed08f620a1db2",
          "sha256": "01e8ceebcbd993deb0643fb42db6c78e7553bfd1d60c23abf7fa4161dda1f467",
          "sha1": "6a2ec0ed60295320ea4039402fad1b73ad13d678",
          "md5": "e052287c6a2cfe6b8d0d94718785a0fa"
        }
      ]
    }
  ]
}
