{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-meta/build.7/model-meta-build.7.module",
    "group": "net.lepinoid",
    "module": "model-meta",
    "version": "build.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.7.jar",
          "url": "model-meta-jvm-build.7.jar",
          "size": 19775,
          "sha512": "023c934cf5de81b63c9cae4c2e69429ac46514a98f8a4aa3468ef1bb31c917d6b22881f4a5585aadde6cdc28c688a7a9c414941cebfef4fc7295bb6a9f830e29",
          "sha256": "48957003e80d1047514c7abc334da3a3e3f465b8064072df30f7ffec6592709e",
          "sha1": "df372168a1c1f4b3d04d1efb2e8de9b929333a54",
          "md5": "8fc308dbfb54e791b06d3c64fda6e0e8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "uuid-serializer",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.lepinoid",
          "module": "bb-data-structure",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "model-meta-jvm-build.7.jar",
          "url": "model-meta-jvm-build.7.jar",
          "size": 19775,
          "sha512": "023c934cf5de81b63c9cae4c2e69429ac46514a98f8a4aa3468ef1bb31c917d6b22881f4a5585aadde6cdc28c688a7a9c414941cebfef4fc7295bb6a9f830e29",
          "sha256": "48957003e80d1047514c7abc334da3a3e3f465b8064072df30f7ffec6592709e",
          "sha1": "df372168a1c1f4b3d04d1efb2e8de9b929333a54",
          "md5": "8fc308dbfb54e791b06d3c64fda6e0e8"
        }
      ]
    }
  ]
}
