{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lepinoid",
    "module": "lepinoid-client-fabric",
    "version": "1.19.1+build.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.10.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.10.jar",
          "size": 66712,
          "sha512": "2ac3aff7657265740f24fefb4a5cab3ad92abdbda6f0d09d162980ac61bade7e356efd869c49b67397b5b17e7fd729d961a956cf9225144f8031d012363c25dc",
          "sha256": "ee60c2539db3f934b2e204e7f6dc7e2e90a031170b74bbefacbd3f1b6da9ed46",
          "sha1": "0b6f25d7bbb0151d6e561477a16a58ae4919f26b",
          "md5": "b23b4d42084ae4e15824c23f8d44eb9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lepinoid",
          "module": "lepinoid-client-protocol",
          "version": {
            "requires": "1.19.1+build.10"
          }
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.9+e62f51a395"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.1.5+0c17ea9695"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.1.0+33fbc73895"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.21+23c4cfef95"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.5.6+5f1a85e095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.18+9ff28f4095"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "1.2.1+3082331495"
          }
        }
      ],
      "files": [
        {
          "name": "lepinoid-client-fabric-1.19.1+build.10.jar",
          "url": "lepinoid-client-fabric-1.19.1+build.10.jar",
          "size": 66712,
          "sha512": "2ac3aff7657265740f24fefb4a5cab3ad92abdbda6f0d09d162980ac61bade7e356efd869c49b67397b5b17e7fd729d961a956cf9225144f8031d012363c25dc",
          "sha256": "ee60c2539db3f934b2e204e7f6dc7e2e90a031170b74bbefacbd3f1b6da9ed46",
          "sha1": "0b6f25d7bbb0151d6e561477a16a58ae4919f26b",
          "md5": "b23b4d42084ae4e15824c23f8d44eb9f"
        }
      ]
    }
  ]
}
